import { DatabaseState } from './schema';

export const initialDatabaseState: DatabaseState = {
  company: {
    id: 'comp-1',
    name: 'İŞBEY Teknoloji ve Ticaret A.Ş.',
    title: 'İŞBEY Bilgi Teknolojileri ve Ticaret Anonim Şirketi',
    taxNumber: '4810592817',
    taxOffice: 'Kadıköy',
    phone: '+90 (216) 555 01 23',
    email: 'info@isbey.com.tr',
    address: 'Atatürk Caddesi No: 45 Kat: 4',
    city: 'İstanbul',
    district: 'Kadıköy',
    currency: '₺',
    costingMethod: 'AVG_COST',
    fiscalYear: 2026,
  },
  activeTenantId: 'tnt-isbey',
  tenants: [
    {
      id: 'tnt-isbey',
      companyCode: 'ISB-000001',
      name: 'İŞBEY Teknoloji ve Ticaret A.Ş.',
      slug: 'isbey-merkez',
      title: 'İŞBEY Bilgi Teknolojileri ve Ticaret Anonim Şirketi',
      taxNumber: '4810592817',
      taxOffice: 'Kadıköy',
      identityNumber: '11223344556',
      mersisNo: '0481059281700001',
      email: 'info@isbey.com.tr',
      phone: '+90 (216) 555 01 23',
      gsm: '0532 100 20 30',
      website: 'https://isbey.com.tr',
      address: 'Atatürk Caddesi No: 45 Kat: 4 Kadıköy / İSTANBUL',
      city: 'İstanbul',
      district: 'Kadıköy',
      postalCode: '34710',
      plan: 'ENTERPRISE',
      status: 'ACTIVE',
      maxUsers: 25,
      currentUsers: 3,
      maxInvoicesPerMonth: 10000,
      eInvoiceCredits: 943,
      storageLimitMb: 5120,
      storageUsedMb: 142,
      activeModules: ['POS', 'STOK', 'CARI', 'FATURA', 'TEKLIF_SIPARIS', 'IRSALIYE', 'BANKA', 'KASA', 'CEK_SENET', 'E_FATURA', 'PERSONEL', 'RAPORLAR', 'AI_ASISTAN', 'FORM_DESIGNER'],
      activeServices: [
        { serviceCode: 'PRE_ACCOUNTING', serviceName: 'Ön Muhasebe', startDate: '2026-01-01', endDate: '2027-12-31', status: 'ACTIVE' },
        { serviceCode: 'CARI', serviceName: 'Cari Hesaplar', startDate: '2026-01-01', endDate: '2027-12-31', status: 'ACTIVE' },
        { serviceCode: 'STOK', serviceName: 'Stok Yönetimi', startDate: '2026-01-01', endDate: '2027-12-31', status: 'ACTIVE' },
        { serviceCode: 'FATURA', serviceName: 'Fatura Modülü', startDate: '2026-01-01', endDate: '2027-12-31', status: 'ACTIVE' },
        { serviceCode: 'EFATURA', serviceName: 'e-Fatura Entegrasyonu', startDate: '2026-01-01', endDate: '2027-12-31', status: 'ACTIVE' },
        { serviceCode: 'EARSIV', serviceName: 'e-Arşiv Fatura', startDate: '2026-01-01', endDate: '2027-12-31', status: 'ACTIVE' },
        { serviceCode: 'EIRSALIYE', serviceName: 'e-İrsaliye', startDate: '2026-01-01', endDate: '2027-12-31', status: 'ACTIVE' },
        { serviceCode: 'KASA', serviceName: 'Kasa Takibi', startDate: '2026-01-01', endDate: '2027-12-31', status: 'ACTIVE' },
        { serviceCode: 'BANKA', serviceName: 'Banka Hesapları', startDate: '2026-01-01', endDate: '2027-12-31', status: 'ACTIVE' },
        { serviceCode: 'CEK_SENET', serviceName: 'Çek / Senet', startDate: '2026-01-01', endDate: '2027-12-31', status: 'ACTIVE' },
        { serviceCode: 'TEKLIF_SIPARIS', serviceName: 'Teklif & Sipariş', startDate: '2026-01-01', endDate: '2027-12-31', status: 'ACTIVE' },
        { serviceCode: 'PERSONEL', serviceName: 'Personel & Prim', startDate: '2026-01-01', endDate: '2027-12-31', status: 'ACTIVE' },
        { serviceCode: 'RAPOR', serviceName: 'Gelişmiş Raporlar', startDate: '2026-01-01', endDate: '2027-12-31', status: 'ACTIVE' },
        { serviceCode: 'API', serviceName: 'REST API Erişimi', startDate: '2026-01-01', endDate: '2027-12-31', status: 'ACTIVE' },
        { serviceCode: 'FORM_DESIGNER', serviceName: 'Form Tasarımcısı', startDate: '2026-01-01', endDate: '2027-12-31', status: 'ACTIVE' },
        { serviceCode: 'AI_ASISTAN', serviceName: 'AI Asistanı', startDate: '2026-01-01', endDate: '2027-12-31', status: 'ACTIVE' },
      ],
      license: {
        startDate: '2026-01-01',
        endDate: '2027-08-31',
        isTrial: false,
        trialDays: 0,
        status: 'ACTIVE',
      },
      limits: {
        maxUsers: 25,
        maxBranches: 10,
        maxWarehouses: 10,
        maxInvoicesPerMonth: 10000,
        storageLimitMb: 5120,
        storageUsedMb: 142,
      },
      branches: [
        { id: 'br-1', name: 'Kadıköy Genel Merkez', code: 'SB-01', isDefault: true, phone: '+90 (216) 555 01 23', city: 'İstanbul', managerName: 'Vedat Aydın Karakaya' },
        { id: 'br-2', name: 'Ataşehir Finans Ofisi', code: 'SB-02', isDefault: false, phone: '+90 (216) 555 01 99', city: 'İstanbul', managerName: 'Selin Yılmaz' },
      ],
      authorizedPerson: {
        firstName: 'Vedat Aydın',
        lastName: 'Karakaya',
        phone: '0532 100 20 30',
        email: 'admin@isbey.com.tr',
      },
      ownerName: 'Vedat Aydın Karakaya',
      ownerEmail: 'admin@isbey.com.tr',
      ownerPhone: '0532 100 20 30',
      expiresAt: '2027-08-31T23:59:59Z',
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-08-18T10:00:00Z',
      stats: {
        totalCustomers: 28,
        totalProducts: 42,
        totalInvoices: 114,
        totalRevenue: 2450000,
        monthlyInvoiceCount: 38,
        userCount: 3,
        activeServicesCount: 16,
        warehouseCount: 2,
        branchCount: 2,
        lastLoginAt: '2026-08-19T11:30:00Z',
      },
    },
    {
      id: 'tnt-kadikoy',
      companyCode: 'ISB-000002',
      name: 'İŞBEY Kadıköy Perakende Şubesi',
      slug: 'isbey-kadikoy',
      title: 'İŞBEY Perakende Mağazacılık Ltd. Şti.',
      taxNumber: '4810592888',
      taxOffice: 'Kadıköy',
      email: 'kadikoy@isbey.com.tr',
      phone: '+90 (216) 444 12 34',
      gsm: '0535 300 40 50',
      website: 'https://kadikoy.isbey.com.tr',
      address: 'Moda Caddesi No: 12 Kadıköy / İSTANBUL',
      city: 'İstanbul',
      district: 'Kadıköy',
      postalCode: '34714',
      plan: 'PRO',
      status: 'ACTIVE',
      maxUsers: 5,
      currentUsers: 2,
      maxInvoicesPerMonth: 2500,
      eInvoiceCredits: 250,
      storageLimitMb: 2048,
      storageUsedMb: 68,
      activeModules: ['POS', 'STOK', 'CARI', 'FATURA', 'KASA', 'E_FATURA', 'RAPORLAR'],
      activeServices: [
        { serviceCode: 'PRE_ACCOUNTING', serviceName: 'Ön Muhasebe', startDate: '2026-02-10', endDate: '2027-03-15', status: 'ACTIVE' },
        { serviceCode: 'CARI', serviceName: 'Cari Hesaplar', startDate: '2026-02-10', endDate: '2027-03-15', status: 'ACTIVE' },
        { serviceCode: 'STOK', serviceName: 'Stok Yönetimi', startDate: '2026-02-10', endDate: '2027-03-15', status: 'ACTIVE' },
        { serviceCode: 'FATURA', serviceName: 'Fatura Modülü', startDate: '2026-02-10', endDate: '2027-03-15', status: 'ACTIVE' },
        { serviceCode: 'EFATURA', serviceName: 'e-Fatura Entegrasyonu', startDate: '2026-02-10', endDate: '2027-03-15', status: 'ACTIVE' },
        { serviceCode: 'KASA', serviceName: 'Kasa Takibi', startDate: '2026-02-10', endDate: '2027-03-15', status: 'ACTIVE' },
        { serviceCode: 'RAPOR', serviceName: 'Raporlar', startDate: '2026-02-10', endDate: '2027-03-15', status: 'ACTIVE' },
      ],
      license: {
        startDate: '2026-02-10',
        endDate: '2027-03-15',
        isTrial: false,
        trialDays: 0,
        status: 'ACTIVE',
      },
      limits: {
        maxUsers: 5,
        maxBranches: 2,
        maxWarehouses: 2,
        maxInvoicesPerMonth: 2500,
        storageLimitMb: 2048,
        storageUsedMb: 68,
      },
      authorizedPerson: {
        firstName: 'Ahmet',
        lastName: 'Çelik',
        phone: '0535 300 40 50',
        email: 'ahmet@isbey.com.tr',
      },
      ownerName: 'Ahmet Çelik',
      ownerEmail: 'ahmet@isbey.com.tr',
      ownerPhone: '0535 300 40 50',
      expiresAt: '2027-03-15T23:59:59Z',
      createdAt: '2026-02-10T00:00:00Z',
      updatedAt: '2026-08-15T10:00:00Z',
      stats: {
        totalCustomers: 12,
        totalProducts: 24,
        totalInvoices: 52,
        totalRevenue: 480000,
        monthlyInvoiceCount: 19,
        userCount: 2,
        activeServicesCount: 7,
        warehouseCount: 1,
        branchCount: 1,
        lastLoginAt: '2026-08-18T14:15:00Z',
      },
    },
    {
      id: 'tnt-ankara',
      companyCode: 'ISB-000003',
      name: 'İŞBEY İç Anadolu Bölge Dağıtım',
      slug: 'isbey-ankara',
      title: 'İŞBEY Lojistik Dağıtım ve Ticaret A.Ş.',
      taxNumber: '1092837465',
      taxOffice: 'Çankaya',
      email: 'ankara@isbey.com.tr',
      phone: '+90 (312) 333 44 55',
      gsm: '0542 555 66 77',
      website: 'https://ankara.isbey.com.tr',
      address: 'Ostim OSB 100. Yıl Bulvarı No: 88 Yenimahalle / ANKARA',
      city: 'Ankara',
      district: 'Yenimahalle',
      postalCode: '06374',
      plan: 'PRO',
      status: 'ACTIVE',
      maxUsers: 8,
      currentUsers: 3,
      maxInvoicesPerMonth: 4000,
      eInvoiceCredits: 180,
      storageLimitMb: 2048,
      storageUsedMb: 95,
      activeModules: ['STOK', 'CARI', 'FATURA', 'IRSALIYE', 'BANKA', 'KASA', 'RAPORLAR'],
      activeServices: [
        { serviceCode: 'PRE_ACCOUNTING', serviceName: 'Ön Muhasebe', startDate: '2026-03-01', endDate: '2026-12-31', status: 'ACTIVE' },
        { serviceCode: 'CARI', serviceName: 'Cari Hesaplar', startDate: '2026-03-01', endDate: '2026-12-31', status: 'ACTIVE' },
        { serviceCode: 'STOK', serviceName: 'Stok Yönetimi', startDate: '2026-03-01', endDate: '2026-12-31', status: 'ACTIVE' },
        { serviceCode: 'FATURA', serviceName: 'Fatura Modülü', startDate: '2026-03-01', endDate: '2026-12-31', status: 'ACTIVE' },
        { serviceCode: 'IRSALIYE', serviceName: 'İrsaliye', startDate: '2026-03-01', endDate: '2026-12-31', status: 'ACTIVE' },
        { serviceCode: 'KASA', serviceName: 'Kasa Takibi', startDate: '2026-03-01', endDate: '2026-12-31', status: 'ACTIVE' },
        { serviceCode: 'BANKA', serviceName: 'Banka Hesapları', startDate: '2026-03-01', endDate: '2026-12-31', status: 'ACTIVE' },
        { serviceCode: 'RAPOR', serviceName: 'Raporlar', startDate: '2026-03-01', endDate: '2026-12-31', status: 'ACTIVE' },
      ],
      license: {
        startDate: '2026-03-01',
        endDate: '2026-12-31',
        isTrial: false,
        trialDays: 0,
        status: 'ACTIVE',
      },
      limits: {
        maxUsers: 8,
        maxBranches: 3,
        maxWarehouses: 3,
        maxInvoicesPerMonth: 4000,
        storageLimitMb: 2048,
        storageUsedMb: 95,
      },
      authorizedPerson: {
        firstName: 'Murat',
        lastName: 'Demir',
        phone: '0542 555 66 77',
        email: 'murat.demir@isbey.com.tr',
      },
      ownerName: 'Murat Demir',
      ownerEmail: 'murat.demir@isbey.com.tr',
      ownerPhone: '0542 555 66 77',
      expiresAt: '2026-12-31T23:59:59Z',
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-08-16T10:00:00Z',
      stats: {
        totalCustomers: 18,
        totalProducts: 35,
        totalInvoices: 67,
        totalRevenue: 890000,
        monthlyInvoiceCount: 22,
        userCount: 3,
        activeServicesCount: 8,
        warehouseCount: 2,
        branchCount: 1,
        lastLoginAt: '2026-08-17T09:40:00Z',
      },
    },
    {
      id: 'tnt-global-lojistik',
      companyCode: 'ISB-000004',
      name: 'Global Lojistik & Antrepo A.Ş.',
      slug: 'global-lojistik',
      title: 'Global Uluslararası Taşımacılık ve Antrepo Hizmetleri A.Ş.',
      taxNumber: '9988776655',
      taxOffice: 'Büyük Mükellefler',
      email: 'operasyon@globallojistik.com.tr',
      phone: '+90 (212) 888 99 00',
      gsm: '0533 888 11 22',
      website: 'https://globallojistik.com.tr',
      address: 'Ambarlı Liman Tesisleri No: 5 Avcılar / İSTANBUL',
      city: 'İstanbul',
      district: 'Avcılar',
      postalCode: '34310',
      plan: 'ENTERPRISE',
      status: 'TRIAL',
      maxUsers: 20,
      currentUsers: 4,
      maxInvoicesPerMonth: 20000,
      eInvoiceCredits: 1200,
      storageLimitMb: 10240,
      storageUsedMb: 310,
      activeModules: ['STOK', 'CARI', 'FATURA', 'TEKLIF_SIPARIS', 'IRSALIYE', 'BANKA', 'KASA', 'CEK_SENET', 'E_FATURA', 'PERSONEL', 'RAPORLAR', 'AI_ASISTAN', 'FORM_DESIGNER'],
      activeServices: [
        { serviceCode: 'PRE_ACCOUNTING', serviceName: 'Ön Muhasebe', startDate: '2026-08-01', endDate: '2026-09-30', status: 'ACTIVE' },
        { serviceCode: 'CARI', serviceName: 'Cari Hesaplar', startDate: '2026-08-01', endDate: '2026-09-30', status: 'ACTIVE' },
        { serviceCode: 'STOK', serviceName: 'Stok Yönetimi', startDate: '2026-08-01', endDate: '2026-09-30', status: 'ACTIVE' },
        { serviceCode: 'FATURA', serviceName: 'Fatura Modülü', startDate: '2026-08-01', endDate: '2026-09-30', status: 'ACTIVE' },
        { serviceCode: 'EFATURA', serviceName: 'e-Fatura Entegrasyonu', startDate: '2026-08-01', endDate: '2026-09-30', status: 'ACTIVE' },
        { serviceCode: 'EARSIV', serviceName: 'e-Arşiv Fatura', startDate: '2026-08-01', endDate: '2026-09-30', status: 'ACTIVE' },
        { serviceCode: 'EIRSALIYE', serviceName: 'e-İrsaliye', startDate: '2026-08-01', endDate: '2026-09-30', status: 'ACTIVE' },
        { serviceCode: 'DEPO', serviceName: 'Depo & Antrepo', startDate: '2026-08-01', endDate: '2026-09-30', status: 'ACTIVE' },
        { serviceCode: 'API', serviceName: 'REST API', startDate: '2026-08-01', endDate: '2026-09-30', status: 'ACTIVE' },
      ],
      license: {
        startDate: '2026-08-01',
        endDate: '2026-09-30',
        isTrial: true,
        trialDays: 60,
        status: 'ACTIVE',
      },
      limits: {
        maxUsers: 20,
        maxBranches: 5,
        maxWarehouses: 8,
        maxInvoicesPerMonth: 20000,
        storageLimitMb: 10240,
        storageUsedMb: 310,
      },
      authorizedPerson: {
        firstName: 'Cemil',
        lastName: 'Karaca',
        phone: '0533 888 11 22',
        email: 'cemil@globallojistik.com.tr',
      },
      ownerName: 'Cemil Karaca',
      ownerEmail: 'cemil@globallojistik.com.tr',
      ownerPhone: '0533 888 11 22',
      expiresAt: '2026-09-30T23:59:59Z',
      createdAt: '2026-08-01T00:00:00Z',
      updatedAt: '2026-08-18T10:00:00Z',
      stats: {
        totalCustomers: 45,
        totalProducts: 60,
        totalInvoices: 180,
        totalRevenue: 5200000,
        monthlyInvoiceCount: 64,
        userCount: 4,
        activeServicesCount: 9,
        warehouseCount: 4,
        branchCount: 2,
        lastLoginAt: '2026-08-18T16:00:00Z',
      },
    },
  ],
  users: [
    {
      id: 'usr-1',
      username: 'admin',
      fullName: 'Yönetici Kullanıcı',
      email: 'admin@isbey.com.tr',
      phone: '0532 100 20 30',
      role: 'SUPER_ADMIN',
      passwordHash: 'admin123',
      active: true,
      createdAt: '2026-01-01T09:00:00Z',
      lastLoginAt: '2026-08-15T14:30:00Z',
    },
    {
      id: 'usr-2',
      username: 'muhasebe',
      fullName: 'Selin Yılmaz',
      email: 'selin@isbey.com.tr',
      phone: '0533 200 30 40',
      role: 'MUHASEBE',
      passwordHash: 'muhasebe123',
      active: true,
      createdAt: '2026-01-10T09:00:00Z',
      lastLoginAt: '2026-08-15T11:20:00Z',
    },
    {
      id: 'usr-3',
      username: 'kasiyer',
      fullName: 'Ahmet Çelik',
      email: 'ahmet@isbey.com.tr',
      phone: '0535 300 40 50',
      role: 'SATIS',
      passwordHash: 'kasiyer123',
      active: true,
      createdAt: '2026-02-01T09:00:00Z',
      lastLoginAt: '2026-08-15T16:45:00Z',
    },
    // FAZ 20: Rol bazlı erişim testleri için test kullanıcıları
    {
      id: 'usr-4',
      username: 'firmaadmin',
      fullName: 'Zeynep Demir',
      email: 'zeynep@isbey.com.tr',
      phone: '0536 400 50 60',
      role: 'COMPANY_ADMIN',
      passwordHash: 'firmaadmin123',
      active: true,
      companyId: 'tnt-isbey',
      allowedCompanyIds: ['tnt-isbey'],
      createdAt: '2026-03-01T09:00:00Z',
    },
    {
      id: 'usr-5',
      username: 'rapor',
      fullName: 'Murat Kaya',
      email: 'murat@isbey.com.tr',
      phone: '0537 500 60 70',
      role: 'RAPOR',
      passwordHash: 'rapor123',
      active: true,
      companyId: 'tnt-isbey',
      allowedCompanyIds: ['tnt-isbey'],
      createdAt: '2026-03-15T09:00:00Z',
    },
    // FAZ 20: Negatif erişim testi için PASİF kullanıcı (login reddedilmeli)
    {
      id: 'usr-6',
      username: 'pasifkullanici',
      fullName: 'Ece Arslan',
      email: 'ece@isbey.com.tr',
      phone: '0538 600 70 80',
      role: 'SATIS',
      passwordHash: 'pasif123',
      active: false,
      companyId: 'tnt-isbey',
      allowedCompanyIds: ['tnt-isbey'],
      createdAt: '2026-04-01T09:00:00Z',
    },
  ],
  productGroups: [
    { id: 'grp-1', name: 'Bilgisayar & Donanım', code: 'GRP-BIL' },
    { id: 'grp-2', name: 'Ofis Malzemeleri & Kırtasiye', code: 'GRP-OFS' },
    { id: 'grp-3', name: 'Ağ & Güvenlik Sistemleri', code: 'GRP-NET' },
    { id: 'grp-4', name: 'Aksesuarlar & Kablolar', code: 'GRP-ACC' },
  ],
  warehouses: [
    { id: 'wh-1', name: 'Merkez Depo', code: 'DEP-01', isDefault: true, address: 'Merkez Binası Zemin Kat' },
    { id: 'wh-2', name: 'Kadıköy Şube Depo', code: 'DEP-02', isDefault: false, address: 'Kadıköy Şube Depo Alanı' },
  ],
  products: [
    {
      id: 'prd-1',
      barcode: '8690123456789',
      code: 'STK-001',
      name: 'Kablosuz Lazer Sessiz Mouse (Siyah)',
      groupId: 'grp-1',
      groupName: 'Bilgisayar & Donanım',
      unit: 'Adet',
      purchasePrice: 280.00,
      salePrice: 490.00,
      vatRate: 20,
      criticalStock: 10,
      currentStock: 48,
      warehouseId: 'wh-1',
      warehouseName: 'Merkez Depo',
      description: '2.4GHz + Bluetooth Çift Modlu',
      imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=200&h=200&fit=crop&auto=format&q=80',
      active: true,
      createdAt: '2026-01-15T10:00:00Z',
      updatedAt: '2026-08-15T10:00:00Z',
    },
    {
      id: 'prd-2',
      barcode: '8690987654321',
      code: 'STK-002',
      name: 'Mekanik RGB Oyuncu Klavyesi (Mavi Switch)',
      groupId: 'grp-1',
      groupName: 'Bilgisayar & Donanım',
      unit: 'Adet',
      purchasePrice: 750.00,
      salePrice: 1290.00,
      vatRate: 20,
      criticalStock: 8,
      currentStock: 19,
      warehouseId: 'wh-1',
      warehouseName: 'Merkez Depo',
      description: 'Türkçe Q Dizilim, Alüminyum Gövde',
      imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=200&h=200&fit=crop&auto=format&q=80',
      active: true,
      createdAt: '2026-01-15T10:00:00Z',
      updatedAt: '2026-08-15T10:00:00Z',
    },
    {
      id: 'prd-3',
      barcode: '8691122334455',
      code: 'STK-003',
      name: '27" 144Hz 1ms IPS Profesyonel Monitör',
      groupId: 'grp-1',
      groupName: 'Bilgisayar & Donanım',
      unit: 'Adet',
      purchasePrice: 4200.00,
      salePrice: 6750.00,
      vatRate: 20,
      criticalStock: 5,
      currentStock: 7,
      warehouseId: 'wh-1',
      warehouseName: 'Merkez Depo',
      description: 'QHD 2560x1440 Pivot Ayak',
      imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=200&h=200&fit=crop&auto=format&q=80',
      active: true,
      createdAt: '2026-02-01T10:00:00Z',
      updatedAt: '2026-08-15T10:00:00Z',
    },
    {
      id: 'prd-4',
      barcode: '8695566778899',
      code: 'STK-004',
      name: 'A4 80gr Fotokopi Kağıdı (5x500 Paket Koli)',
      groupId: 'grp-2',
      groupName: 'Ofis Malzemeleri & Kırtasiye',
      unit: 'Koli',
      purchasePrice: 420.00,
      salePrice: 620.00,
      vatRate: 20,
      criticalStock: 15,
      currentStock: 3, // KRİTİK STOK!
      warehouseId: 'wh-1',
      warehouseName: 'Merkez Depo',
      description: 'Yüksek beyazlık derecesi, lazer uyumlu',
      imageUrl: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=200&h=200&fit=crop&auto=format&q=80',
      active: true,
      createdAt: '2026-02-05T10:00:00Z',
      updatedAt: '2026-08-15T10:00:00Z',
    },
    {
      id: 'prd-5',
      barcode: '8697788990011',
      code: 'STK-005',
      name: 'Cat6 UTP RJ45 Ağ Kablosu (3 Metre)',
      groupId: 'grp-3',
      groupName: 'Ağ & Güvenlik Sistemleri',
      unit: 'Adet',
      purchasePrice: 25.00,
      salePrice: 65.00,
      vatRate: 20,
      criticalStock: 25,
      currentStock: 120,
      warehouseId: 'wh-1',
      warehouseName: 'Merkez Depo',
      description: 'Saf Bakır İletken Gigabit Hız',
      imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=200&h=200&fit=crop&auto=format&q=80',
      active: true,
      createdAt: '2026-02-10T10:00:00Z',
      updatedAt: '2026-08-15T10:00:00Z',
    },
    {
      id: 'prd-6',
      barcode: '8698899001122',
      code: 'STK-006',
      name: '1TB NVMe PCIe 4.0 SSD (7000MB/s)',
      groupId: 'grp-1',
      groupName: 'Bilgisayar & Donanım',
      unit: 'Adet',
      purchasePrice: 2400.00,
      salePrice: 3850.00,
      vatRate: 20,
      criticalStock: 6,
      currentStock: 4, // KRİTİK STOK!
      warehouseId: 'wh-1',
      warehouseName: 'Merkez Depo',
      description: 'M.2 2280 Soğutucu Bloklu',
      imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=200&h=200&fit=crop&auto=format&q=80',
      active: true,
      createdAt: '2026-03-01T10:00:00Z',
      updatedAt: '2026-08-15T10:00:00Z',
    },
    {
      id: 'prd-7',
      barcode: '8699900112233',
      code: 'STK-007',
      name: 'Ergonomik Fileli Ofis Çalışma Koltuğu',
      groupId: 'grp-2',
      groupName: 'Ofis Malzemeleri & Kırtasiye',
      unit: 'Adet',
      purchasePrice: 2100.00,
      salePrice: 3450.00,
      vatRate: 10,
      criticalStock: 4,
      currentStock: 11,
      warehouseId: 'wh-1',
      warehouseName: 'Merkez Depo',
      description: 'Bel destekli, 3D hareketli kolçak',
      imageUrl: 'https://images.unsplash.com/photo-1580481077197-28d844196160?w=200&h=200&fit=crop&auto=format&q=80',
      active: true,
      createdAt: '2026-03-15T10:00:00Z',
      updatedAt: '2026-08-15T10:00:00Z',
    },
  ],
  customers: [
    {
      id: 'cust-1',
      code: 'CAR-001',
      title: 'ABC Bilişim ve Yazılım Danışmanlık Ltd. Şti.',
      contactName: 'Murat Arslan',
      taxNumber: '1029384756',
      taxOffice: 'Kozyatağı',
      phone: '0216 444 88 99',
      email: 'muhasebe@abcbilisim.com',
      address: 'Kozyatağı Mah. Bayar Cad. No: 12/4',
      city: 'İstanbul',
      district: 'Kadıköy',
      iban: 'TR45 0006 2000 1234 5678 9012 34',
      type: 'CUSTOMER',
      riskLimit: 150000.00,
      maturityDays: 30,
      notes: 'Düzenli alım yapan kurumsal müşteri',
      balance: 48500.00, // 48.500 TL Borçlu (Alacağımız)
      totalDebit: 125000.00,
      totalCredit: 76500.00,
      active: true,
      createdAt: '2026-01-10T10:00:00Z',
      updatedAt: '2026-08-15T10:00:00Z',
    },
    {
      id: 'cust-2',
      code: 'CAR-002',
      title: 'Ege Perakende ve Mağazacılık A.Ş.',
      contactName: 'Canan Güneş',
      taxNumber: '3847291048',
      taxOffice: 'Alsancak',
      phone: '0232 333 22 11',
      email: 'finans@egestore.com',
      address: 'Alsancak Bulvarı No: 88',
      city: 'İzmir',
      district: 'Konak',
      iban: 'TR12 0001 5001 9876 5432 1098 76',
      type: 'CUSTOMER',
      riskLimit: 200000.00,
      maturityDays: 15,
      notes: 'Vadesi 18 gün gecikmiş faturası bulunuyor',
      balance: 82400.00, // 82.400 TL Borçlu (Gecikmiş!)
      totalDebit: 182400.00,
      totalCredit: 100000.00,
      active: true,
      createdAt: '2026-01-20T10:00:00Z',
      updatedAt: '2026-08-15T10:00:00Z',
    },
    {
      id: 'cust-3',
      code: 'CAR-003',
      title: 'Marmara Dağıtım ve Lojistik Ltd. Şti.',
      contactName: 'Kemal Tekin',
      taxNumber: '9988776655',
      taxOffice: 'Tuzla',
      phone: '0216 395 10 20',
      email: 'siparis@marmarada.com',
      address: 'Organize Sanayi Bölgesi 4. Cad. No: 18',
      city: 'İstanbul',
      district: 'Tuzla',
      iban: 'TR88 0006 4000 0011 2233 4455 66',
      type: 'SUPPLIER',
      riskLimit: 500000.00,
      maturityDays: 45,
      notes: 'Ana donanım ve bilgisayar parçası tedarikçimiz',
      balance: -64200.00, // Bizim 64.200 TL borcumuz var
      totalDebit: 150000.00,
      totalCredit: 214200.00,
      active: true,
      createdAt: '2026-01-05T10:00:00Z',
      updatedAt: '2026-08-15T10:00:00Z',
    },
    {
      id: 'cust-4',
      code: 'CAR-004',
      title: 'Özdemir Kırtasiye & Büro Ltd.',
      contactName: 'Hakan Özdemir',
      taxNumber: '4455667788',
      taxOffice: 'Üsküdar',
      phone: '0216 555 77 88',
      email: 'info@ozdemirkirtasiye.com',
      address: 'Hakimiyeti Milliye Cad. No: 102',
      city: 'İstanbul',
      district: 'Üsküdar',
      iban: 'TR33 0006 2000 5544 3322 1100 99',
      type: 'CUSTOMER',
      riskLimit: 75000.00,
      maturityDays: 30,
      notes: 'Haftalık düzenli kağıt ve sarf alımı',
      balance: 16800.00,
      totalDebit: 45000.00,
      totalCredit: 28200.00,
      active: true,
      createdAt: '2026-02-12T10:00:00Z',
      updatedAt: '2026-08-15T10:00:00Z',
    },
    {
      id: 'cust-5',
      code: 'CAR-005',
      title: 'Global Elektronik İthalat A.Ş.',
      contactName: 'Serdar Çetin',
      taxNumber: '7788990011',
      taxOffice: 'Güneşli',
      phone: '0212 654 32 10',
      email: 'ithalat@globalelektronik.com.tr',
      address: 'Basın Ekspres Yolu No: 40/B',
      city: 'İstanbul',
      district: 'Bağcılar',
      iban: 'TR77 0006 7000 8899 0011 2233 44',
      type: 'SUPPLIER',
      riskLimit: 400000.00,
      maturityDays: 60,
      notes: 'SSD ve Monitör Distribütörü',
      balance: -42500.00,
      totalDebit: 100000.00,
      totalCredit: 142500.00,
      active: true,
      createdAt: '2026-01-08T10:00:00Z',
      updatedAt: '2026-08-15T10:00:00Z',
    },
  ],
  cashRegisters: [
    {
      id: 'cash-1',
      name: 'Merkez TL Kasası',
      code: 'KAS-01',
      isDefault: true,
      balance: 34850.00,
      currency: '₺',
      description: 'Genel merkez nakit tahsilat ve ödeme kasası',
      active: true,
    },
    {
      id: 'cash-2',
      name: 'Hızlı POS & Satış Kasası',
      code: 'KAS-02',
      isDefault: false,
      balance: 17450.00,
      currency: '₺',
      description: 'Mağaza içi günlük perakende satış kasası',
      active: true,
    },
  ],
  bankAccounts: [
    {
      id: 'bnk-1',
      bankName: 'Garanti BBVA',
      accountName: 'Kadıköy Ticari TL Hesabı',
      accountNo: '6200145',
      branchName: 'Kadıköy Rıhtım Şubesi',
      iban: 'TR56 0006 2000 0001 2345 6789 01',
      currency: '₺',
      balance: 112500.00,
      isDefault: true,
      active: true,
    },
    {
      id: 'bnk-2',
      bankName: 'Yapı Kredi',
      accountName: 'Kurumsal Ana Hesap',
      accountNo: '9845120',
      branchName: 'Kozyatağı Ticari Şube',
      iban: 'TR12 0006 7000 0009 8765 4321 02',
      currency: '₺',
      balance: 71700.00,
      isDefault: false,
      active: true,
    },
  ],
  checksNotes: [
    {
      id: 'chk-1',
      type: 'INCOMING_CHECK',
      documentNo: 'ÇEK-2026-001',
      bankName: 'İş Bankası',
      branchName: 'Kadıköy',
      accountNo: '3049281',
      checkNumber: '849201',
      drawer: 'ABC Bilişim Ltd.',
      amount: 25000.00,
      issueDate: '2026-07-20',
      maturityDate: '2026-08-25', // 10 gün sonra vadeli
      customerId: 'cust-1',
      customerTitle: 'ABC Bilişim ve Yazılım Danışmanlık Ltd. Şti.',
      status: 'IN_PORTFOLIO',
      description: 'Fatura ödemesine mahsuben alınan çek',
      userId: 'usr-1',
      createdAt: '2026-07-20T11:00:00Z',
    },
    {
      id: 'chk-2',
      type: 'OUTGOING_CHECK',
      documentNo: 'ÇEK-2026-002',
      bankName: 'Garanti BBVA',
      branchName: 'Kadıköy Rıhtım',
      accountNo: '6200145',
      checkNumber: '109283',
      drawer: 'İŞBEY Teknoloji ve Ticaret A.Ş.',
      amount: 40000.00,
      issueDate: '2026-07-15',
      maturityDate: '2026-08-30',
      customerId: 'cust-3',
      customerTitle: 'Marmara Dağıtım ve Lojistik Ltd. Şti.',
      status: 'IN_PORTFOLIO',
      description: 'Donanım alımı için verilen çek',
      userId: 'usr-1',
      createdAt: '2026-07-15T14:30:00Z',
    },
  ],
  employees: [
    {
      id: 'emp-1',
      code: 'PER-001',
      fullName: 'Ahmet Çelik',
      phone: '0535 300 40 50',
      email: 'ahmet@isbey.com.tr',
      department: 'Satış & Pazarlama',
      title: 'Kıdemli Satış Temsilcisi',
      salary: 32500.00,
      commissionRate: 2.5,
      totalSales: 245000.00,
      totalCommission: 6125.00,
      totalPaid: 35000.00,
      balance: 3625.00,
      active: true,
      createdAt: '2026-01-01T09:00:00Z',
    },
    {
      id: 'emp-2',
      code: 'PER-002',
      fullName: 'Selin Yılmaz',
      phone: '0533 200 30 40',
      email: 'selin@isbey.com.tr',
      department: 'Muhasebe & Finans',
      title: 'Mali İşler Uzmanı',
      salary: 38000.00,
      commissionRate: 0,
      totalSales: 0,
      totalCommission: 0,
      totalPaid: 38000.00,
      balance: 0,
      active: true,
      createdAt: '2026-01-01T09:00:00Z',
    },
  ],
  employeeTransactions: [],
  stockMovements: [
    {
      id: 'sm-1',
      productId: 'prd-1',
      productCode: 'STK-001',
      productName: 'Kablosuz Lazer Sessiz Mouse (Siyah)',
      warehouseId: 'wh-1',
      warehouseName: 'Merkez Depo',
      documentNo: 'AL-2026-000001',
      documentType: 'INVOICE',
      movementType: 'PURCHASE',
      quantity: 50,
      direction: 'IN',
      unitPrice: 280.00,
      totalAmount: 14000.00,
      date: '2026-08-01',
      userId: 'usr-1',
      createdAt: '2026-08-01T10:00:00Z',
    },
    {
      id: 'sm-2',
      productId: 'prd-1',
      productCode: 'STK-001',
      productName: 'Kablosuz Lazer Sessiz Mouse (Siyah)',
      warehouseId: 'wh-1',
      warehouseName: 'Merkez Depo',
      documentNo: 'SAT-2026-000001',
      documentType: 'INVOICE',
      movementType: 'SALE',
      quantity: 2,
      direction: 'OUT',
      unitPrice: 490.00,
      totalAmount: 980.00,
      date: '2026-08-15',
      userId: 'usr-1',
      createdAt: '2026-08-15T11:00:00Z',
    },
  ],
  invoices: [
    {
      id: 'inv-1',
      invoiceNo: 'SAT-2026-000001',
      type: 'SALES',
      customerId: 'cust-1',
      customerCode: 'CAR-001',
      customerTitle: 'ABC Bilişim ve Yazılım Danışmanlık Ltd. Şti.',
      date: '2026-08-15',
      maturityDate: '2026-09-14',
      subTotal: 14750.00,
      totalDiscount: 0,
      totalVat: 2950.00,
      grandTotal: 17700.00,
      paidAmount: 0,
      paymentStatus: 'UNPAID',
      paymentType: 'OPEN_ACCOUNT',
      warehouseId: 'wh-1',
      notes: 'Yazılım ekibi için sipariş edilen donanımlar',
      items: [
        {
          id: 'item-1',
          invoiceId: 'inv-1',
          productId: 'prd-3',
          productCode: 'STK-003',
          productName: '27" 144Hz 1ms IPS Profesyonel Monitör',
          barcode: '8691122334455',
          quantity: 2,
          unit: 'Adet',
          unitPrice: 6750.00,
          discount1: 0,
          discount2: 0,
          discountAmount: 0,
          vatRate: 20,
          vatAmount: 2700.00,
          vatIncluded: false,
          lineTotal: 13500.00,
          lineGrandTotal: 16200.00,
        },
        {
          id: 'item-2',
          invoiceId: 'inv-1',
          productId: 'prd-2',
          productCode: 'STK-002',
          productName: 'Mekanik RGB Oyuncu Klavyesi (Mavi Switch)',
          barcode: '8690987654321',
          quantity: 1,
          unit: 'Adet',
          unitPrice: 1250.00,
          discount1: 0,
          discount2: 0,
          discountAmount: 0,
          vatRate: 20,
          vatAmount: 250.00,
          vatIncluded: false,
          lineTotal: 1250.00,
          lineGrandTotal: 1500.00,
        },
      ],
      userId: 'usr-1',
      isDeleted: false,
      createdAt: '2026-08-15T11:00:00Z',
      updatedAt: '2026-08-15T11:00:00Z',
    },
    {
      id: 'inv-2',
      invoiceNo: 'SAT-2026-000002',
      type: 'RETAIL_POS',
      customerId: 'cust-4',
      customerCode: 'CAR-004',
      customerTitle: 'Özdemir Kırtasiye & Büro Ltd.',
      date: '2026-08-15',
      maturityDate: '2026-08-15',
      subTotal: 1240.00,
      totalDiscount: 62.00,
      totalVat: 235.60,
      grandTotal: 1413.60,
      paidAmount: 1413.60,
      paymentStatus: 'PAID',
      paymentType: 'CASH',
      cashRegisterId: 'cash-2',
      warehouseId: 'wh-1',
      notes: 'Hızlı Kasa Satışı',
      items: [
        {
          id: 'item-3',
          invoiceId: 'inv-2',
          productId: 'prd-4',
          productCode: 'STK-004',
          productName: 'A4 80gr Fotokopi Kağıdı (5x500 Paket Koli)',
          barcode: '8695566778899',
          quantity: 2,
          unit: 'Koli',
          unitPrice: 620.00,
          discount1: 5,
          discount2: 0,
          discountAmount: 62.00,
          vatRate: 20,
          vatAmount: 235.60,
          vatIncluded: false,
          lineTotal: 1178.00,
          lineGrandTotal: 1413.60,
        },
      ],
      userId: 'usr-3',
      isDeleted: false,
      createdAt: '2026-08-15T14:15:00Z',
      updatedAt: '2026-08-15T14:15:00Z',
    },
  ],
  currentTransactions: [
    {
      id: 'ctx-1',
      customerId: 'cust-1',
      customerCode: 'CAR-001',
      customerTitle: 'ABC Bilişim ve Yazılım Danışmanlık Ltd. Şti.',
      documentNo: 'SAT-2026-000001',
      documentType: 'SALES_INVOICE',
      date: '2026-08-15',
      maturityDate: '2026-09-14',
      debit: 17700.00,
      credit: 0,
      balance: 48500.00,
      description: 'SAT-2026-000001 nolu Satış Faturası',
      relatedInvoiceId: 'inv-1',
      userId: 'usr-1',
      createdAt: '2026-08-15T11:00:00Z',
    },
    {
      id: 'ctx-2',
      customerId: 'cust-2',
      customerCode: 'CAR-002',
      customerTitle: 'Ege Perakende ve Mağazacılık A.Ş.',
      documentNo: 'SAT-2026-000000',
      documentType: 'SALES_INVOICE',
      date: '2026-07-10',
      maturityDate: '2026-07-25', // Vadesi 21 gün geçmiş!
      debit: 82400.00,
      credit: 0,
      balance: 82400.00,
      description: 'Toplu Monitör ve Donanım Satışı (GECİKMİŞ VADE)',
      userId: 'usr-1',
      createdAt: '2026-07-10T10:00:00Z',
    },
  ],
  cashTransactions: [
    {
      id: 'cx-1',
      cashRegisterId: 'cash-2',
      cashRegisterName: 'Hızlı POS & Satış Kasası',
      documentNo: 'POS-2026-000002',
      type: 'COLLECTION',
      direction: 'IN',
      amount: 1413.60,
      date: '2026-08-15',
      customerId: 'cust-4',
      customerTitle: 'Özdemir Kırtasiye & Büro Ltd.',
      category: 'Perakende Satış Tahsilatı',
      description: 'SAT-2026-000002 nolu perakende peşin satış',
      userId: 'usr-3',
      createdAt: '2026-08-15T14:15:00Z',
    },
  ],
  bankTransactions: [
    {
      id: 'bx-1',
      bankAccountId: 'bnk-1',
      bankAccountName: 'Kadıköy Ticari TL Hesabı',
      documentNo: 'EFT-2026-000012',
      type: 'HAVALE_EFT_IN',
      direction: 'IN',
      amount: 15450.00,
      date: '2026-08-15',
      customerId: 'cust-1',
      customerTitle: 'ABC Bilişim ve Yazılım Danışmanlık Ltd. Şti.',
      description: 'Fatura kapama havalesi',
      userId: 'usr-2',
      createdAt: '2026-08-15T09:30:00Z',
    },
  ],
  auditLogs: [
    {
      id: 'log-1',
      userId: 'usr-1',
      username: 'admin',
      action: 'LOGIN',
      module: 'AUTH',
      ipAddress: '127.0.0.1',
      details: 'Sistem yöneticisi başarıyla giriş yaptı',
      timestamp: '2026-08-15T14:30:00Z',
    },
    {
      id: 'log-2',
      userId: 'usr-1',
      username: 'admin',
      action: 'CREATE',
      module: 'INVOICE',
      documentNo: 'SAT-2026-000001',
      ipAddress: '127.0.0.1',
      details: '17.700,00 TL tutarında Satış Faturası kesildi (ABC Bilişim)',
      timestamp: '2026-08-15T11:00:00Z',
    },
  ],
  notifications: [
    {
      id: 'notif-1',
      type: 'OVERDUE_MATURITY',
      severity: 'ERROR',
      title: 'Vadesi Geçmiş Cari Ödeme Uyarısı',
      message: 'Ege Perakende ve Mağazacılık A.Ş. carisinin 82.400,00 TL tutarındaki borcunun vadesi 21 gün gecikmiştir!',
      actionUrl: '/cari',
      isRead: false,
      createdAt: '2026-08-15T08:00:00Z',
    },
    {
      id: 'notif-2',
      type: 'CRITICAL_STOCK',
      severity: 'WARNING',
      title: 'Kritik Stok Uyarısı',
      message: 'A4 80gr Fotokopi Kağıdı ve 1TB NVMe SSD kritik stok seviyesinin altına düşmüştür (3 ve 4 adet kaldı).',
      actionUrl: '/stok',
      isRead: false,
      createdAt: '2026-08-15T08:05:00Z',
    },
    {
      id: 'notif-3',
      type: 'UPCOMING_CHECK',
      severity: 'INFO',
      title: 'Yaklaşan Çek Vadesi',
      message: 'ABC Bilişim firmasına ait 25.000,00 TL tutarındaki çekin vadesine 10 gün kaldı (25.08.2026).',
      actionUrl: '/ceksenet',
      isRead: false,
      createdAt: '2026-08-15T08:10:00Z',
    },
  ],
  quotes: [
    {
      id: 'quote-1',
      quoteNo: 'TEK-2026-000001',
      type: 'SALES_QUOTE',
      customerId: 'cust-1',
      customerCode: 'M-1001',
      customerTitle: 'ABC Bilişim ve Yazılım Danışmanlık Ltd. Şti.',
      date: '2026-08-10',
      validUntil: '2026-08-25',
      subTotal: 34000,
      totalDiscount: 1700,
      totalVat: 6460,
      grandTotal: 38760,
      status: 'SENT',
      termsAndConditions: '1. Fiyatlarımıza %20 KDV dahil edilmiştir.\n2. Teklifimiz 15 gün geçerlidir.\n3. Teslimat süresi sipariş onayından itibaren 3 iş günüdür.',
      notes: 'Kurumsal ofis yenileme donanım paketi teklifidir.',
      items: [
        {
          id: 'qi-1',
          productId: 'prod-1',
          productCode: 'STK-001',
          productName: 'Kablosuz Lazer Sessiz Mouse',
          quantity: 10,
          unit: 'Adet',
          unitPrice: 450,
          discount1: 5,
          discount2: 0,
          vatRate: 20,
          vatAmount: 855,
          lineTotal: 4275,
          lineGrandTotal: 5130,
        },
        {
          id: 'qi-2',
          productId: 'prod-4',
          productCode: 'STK-004',
          productName: '27 inç 4K IPS Profesyonel Monitör',
          quantity: 2,
          unit: 'Adet',
          unitPrice: 14750,
          discount1: 5,
          discount2: 0,
          vatRate: 20,
          vatAmount: 5605,
          lineTotal: 28025,
          lineGrandTotal: 33630,
        },
      ],
      userId: 'usr-1',
      createdAt: '2026-08-10T11:00:00Z',
      updatedAt: '2026-08-10T11:00:00Z',
    },
  ],
  orders: [
    {
      id: 'ord-1',
      orderNo: 'SIP-2026-000001',
      type: 'SALES_ORDER',
      customerId: 'cust-1',
      customerCode: 'M-1001',
      customerTitle: 'ABC Bilişim ve Yazılım Danışmanlık Ltd. Şti.',
      date: '2026-08-12',
      deliveryDate: '2026-08-18',
      subTotal: 18500,
      totalDiscount: 0,
      totalVat: 3700,
      grandTotal: 22200,
      status: 'CONFIRMED',
      warehouseId: 'wh-1',
      notes: 'Merkez ofis teslimatı',
      items: [
        {
          id: 'oi-1',
          productId: 'prod-2',
          productCode: 'STK-002',
          productName: 'Mekanik RGB Klavye Türkçe Q',
          quantity: 10,
          shippedQuantity: 0,
          unit: 'Adet',
          unitPrice: 1850,
          discount1: 0,
          discount2: 0,
          vatRate: 20,
          vatAmount: 3700,
          lineTotal: 18500,
          lineGrandTotal: 22200,
        },
      ],
      userId: 'usr-1',
      createdAt: '2026-08-12T14:30:00Z',
      updatedAt: '2026-08-12T14:30:00Z',
    },
  ],
  waybills: [
    {
      id: 'waybill-1',
      waybillNo: 'IRS-2026-000001',
      type: 'SALES_DESPATCH',
      customerId: 'cust-2',
      customerCode: 'M-1002',
      customerTitle: 'Ege Perakende ve Mağazacılık A.Ş.',
      date: '2026-08-14',
      shipmentDate: '2026-08-14',
      warehouseId: 'wh-1',
      status: 'PENDING',
      carrierTitle: 'Yurtiçi Kargo Dağıtım A.Ş.',
      plateNumber: '34 ER 9081',
      driverName: 'Mustafa Kaya',
      notes: 'Sevk irsaliyesidir, 7 gün içinde faturalaştırılacaktır.',
      items: [
        {
          id: 'wi-1',
          productId: 'prod-1',
          productCode: 'STK-001',
          productName: 'Kablosuz Lazer Sessiz Mouse',
          quantity: 5,
          unit: 'Adet',
          unitPrice: 450,
          vatRate: 20,
          lineTotal: 2250,
        },
      ],
      userId: 'usr-1',
      createdAt: '2026-08-14T10:15:00Z',
      updatedAt: '2026-08-14T10:15:00Z',
    },
  ],
  expenseCategories: [
    { id: 'expcat-1', name: 'Ofis Kirası & Aidat', code: 'KIRA', color: '#6366f1' },
    { id: 'expcat-2', name: 'Elektrik, Su & Isınma', code: 'FATURA', color: '#f59e0b' },
    { id: 'expcat-3', name: 'Personel Yemek & İkram', code: 'YEMEK', color: '#10b981' },
    { id: 'expcat-4', name: 'Akaryakıt & Ulaşım', code: 'ULASIM', color: '#0284c7' },
    { id: 'expcat-5', name: 'Pazarlama & Reklam', code: 'PAZARLAMA', color: '#ec4899' },
    { id: 'expcat-6', name: 'Muhasebe, Hukuk & Danışmanlık', code: 'DANISMANLIK', color: '#8b5cf6' },
    { id: 'expcat-7', name: 'Vergi, Harç & SGK Ödemeleri', code: 'VERGI', color: '#ef4444' },
  ],
  expenses: [
    {
      id: 'exp-1',
      documentNo: 'MAS-2026-000001',
      expenseCategoryId: 'expcat-1',
      expenseCategoryName: 'Ofis Kirası & Aidat',
      title: 'Ağustos 2026 Ofis Kira Ödemesi',
      amount: 25000,
      vatRate: 0,
      vatAmount: 0,
      totalAmount: 25000,
      date: '2026-08-01',
      paymentMethod: 'BANK',
      bankAccountId: 'bnk-1',
      bankAccountName: 'Garanti BBVA - Ticari TL Hesabı',
      receiptNo: 'DEKONT-98214',
      notes: 'Ağustos ayı mülk sahibi kira ödemesi',
      userId: 'usr-2',
      createdAt: '2026-08-01T10:00:00Z',
    },
    {
      id: 'exp-2',
      documentNo: 'MAS-2026-000002',
      expenseCategoryId: 'expcat-3',
      expenseCategoryName: 'Personel Yemek & İkram',
      title: 'Aylık Personel Yemek Kartı Yüklemesi',
      amount: 8000,
      vatRate: 10,
      vatAmount: 800,
      totalAmount: 8800,
      date: '2026-08-05',
      paymentMethod: 'BANK',
      bankAccountId: 'bnk-1',
      bankAccountName: 'Garanti BBVA - Ticari TL Hesabı',
      receiptNo: 'FAT-8921',
      notes: 'Ticket yemek kartı faturalı yüklemesi',
      userId: 'usr-2',
      createdAt: '2026-08-05T11:30:00Z',
    },
    {
      id: 'exp-3',
      documentNo: 'MAS-2026-000003',
      expenseCategoryId: 'expcat-4',
      expenseCategoryName: 'Akaryakıt & Ulaşım',
      title: 'Şirket Aracı Mazot Alımı',
      amount: 2500,
      vatRate: 20,
      vatAmount: 500,
      totalAmount: 3000,
      date: '2026-08-11',
      paymentMethod: 'CASH',
      cashRegisterId: 'cash-1',
      cashRegisterName: 'Merkez Ofis TL Kasası',
      receiptNo: 'FIS-49102',
      notes: '34 ER 9081 plakalı araç sevkiyat yakıtı',
      userId: 'usr-3',
      createdAt: '2026-08-11T16:00:00Z',
    },
  ],
  costCenters: [
    { id: 'cc-1', name: 'Genel Merkez', code: 'GM-001', type: 'BRANCH', description: 'Genel merkez ofisi', active: true, createdAt: '2026-01-01T00:00:00Z' },
    { id: 'cc-2', name: 'Kadıköy Şubesi', code: 'KDK-001', type: 'BRANCH', description: 'Kadıköy satış şubesi', active: true, createdAt: '2026-01-01T00:00:00Z' },
    { id: 'cc-3', name: 'Satış Departmanı', code: 'DEP-SAT', type: 'DEPARTMENT', parentId: 'cc-1', description: 'Satış ve pazarlama', active: true, createdAt: '2026-01-01T00:00:00Z' },
    { id: 'cc-4', name: 'Muhasebe Departmanı', code: 'DEP-MUH', type: 'DEPARTMENT', parentId: 'cc-1', description: 'Muhasebe ve finans', active: true, createdAt: '2026-01-01T00:00:00Z' },
    { id: 'cc-5', name: 'Depo ve Lojistik', code: 'DEP-DEP', type: 'DEPARTMENT', parentId: 'cc-1', description: 'Depolama ve sevkiyat', active: true, createdAt: '2026-01-01T00:00:00Z' },
  ],
  sequences: {
    SALES_INVOICE: { prefix: 'SAT', year: 2026, lastNumber: 2, length: 6 },
    PURCHASE_INVOICE: { prefix: 'ALI', year: 2026, lastNumber: 1, length: 6 },
    PURCHASE_QUOTE: { prefix: 'ALT', year: 2026, lastNumber: 0, length: 6 },
    SALES_QUOTE: { prefix: 'TEK', year: 2026, lastNumber: 1, length: 6 },
    SALES_ORDER: { prefix: 'SIP', year: 2026, lastNumber: 1, length: 6 },
    PURCHASE_ORDER: { prefix: 'ASP', year: 2026, lastNumber: 0, length: 6 },
    WAYBILL: { prefix: 'IRS', year: 2026, lastNumber: 1, length: 6 },
    EXPENSE: { prefix: 'MAS', year: 2026, lastNumber: 3, length: 6 },
    COLLECTION: { prefix: 'TAH', year: 2026, lastNumber: 1, length: 6 },
    PAYMENT: { prefix: 'ODE', year: 2026, lastNumber: 1, length: 6 },
    CASH_TX: { prefix: 'KAS', year: 2026, lastNumber: 1, length: 6 },
    BANK_TX: { prefix: 'BNK', year: 2026, lastNumber: 1, length: 6 },
    CHECK: { prefix: 'CEK', year: 2026, lastNumber: 2, length: 6 },
    COST_CENTER: { prefix: 'MC', year: 2026, lastNumber: 5, length: 6 },
  },
  formDesigns: [
    {
      id: 'fd-default-invoice',
      name: 'Standart A4 Fatura',
      documentType: 'INVOICE_SALES',
      description: 'Standart A4 satış faturası şablonu',
      version: 1,
      isDefault: true,
      isBuiltIn: true,
      paperSize: 'A4',
      orientation: 'portrait',
      marginTop: 10,
      marginBottom: 10,
      marginLeft: 15,
      marginRight: 15,
      sections: [
        {
          id: 'sec-header',
          type: 'HEADER',
          label: 'Başlık',
          order: 1,
          height: 120,
          visible: true,
          elements: [
            { id: 'el-logo', type: 'LOGO', x: 0, y: 0, width: 160, height: 80, props: { objectFit: 'contain' } },
            { id: 'el-company-name', type: 'LABEL', x: 180, y: 8, width: 380, height: 30, props: { dataBinding: 'company.title', fontSize: 16, fontWeight: '700', fontAlign: 'left' } },
            { id: 'el-company-address', type: 'LABEL', x: 180, y: 42, width: 380, height: 20, props: { dataBinding: 'company.address', fontSize: 10, fontAlign: 'left', color: '#475569' } },
            { id: 'el-company-tax', type: 'LABEL', x: 180, y: 64, width: 380, height: 18, props: { dataBinding: 'company.taxInfo', fontSize: 10, fontAlign: 'left', color: '#475569' } },
            { id: 'el-invoice-title', type: 'LABEL', x: 0, y: 90, width: 760, height: 28, props: { value: 'SATIŞ FATURASI', fontSize: 13, fontWeight: '700', fontAlign: 'center', backgroundColor: '#1a56db', color: '#ffffff' } },
          ],
        },
        {
          id: 'sec-customer',
          type: 'CUSTOMER',
          label: 'Müşteri Bilgileri',
          order: 2,
          height: 100,
          visible: true,
          elements: [
            { id: 'el-inv-no-label', type: 'LABEL', x: 0, y: 8, width: 80, height: 18, props: { value: 'Fatura No:', fontSize: 10, fontWeight: '600', color: '#475569' } },
            { id: 'el-inv-no', type: 'LABEL', x: 85, y: 8, width: 200, height: 18, props: { dataBinding: 'invoice.no', fontSize: 11, fontWeight: '700' } },
            { id: 'el-inv-date-label', type: 'LABEL', x: 0, y: 28, width: 80, height: 18, props: { value: 'Tarih:', fontSize: 10, fontWeight: '600', color: '#475569' } },
            { id: 'el-inv-date', type: 'LABEL', x: 85, y: 28, width: 200, height: 18, props: { dataBinding: 'invoice.date', format: 'DATE_TR', fontSize: 10 } },
            { id: 'el-cust-title-label', type: 'LABEL', x: 400, y: 8, width: 80, height: 18, props: { value: 'Müşteri:', fontSize: 10, fontWeight: '600', color: '#475569' } },
            { id: 'el-cust-title', type: 'LABEL', x: 485, y: 8, width: 275, height: 18, props: { dataBinding: 'customer.title', fontSize: 11, fontWeight: '700' } },
            { id: 'el-cust-address', type: 'LABEL', x: 485, y: 28, width: 275, height: 18, props: { dataBinding: 'customer.address', fontSize: 10, color: '#475569' } },
            { id: 'el-cust-tax', type: 'LABEL', x: 485, y: 48, width: 275, height: 18, props: { dataBinding: 'customer.taxInfo', fontSize: 10, color: '#475569' } },
          ],
        },
        {
          id: 'sec-lines',
          type: 'LINES',
          label: 'Ürün Kalemleri',
          order: 3,
          height: 380,
          visible: true,
          elements: [
            { id: 'el-product-table', type: 'PRODUCT_TABLE', x: 0, y: 0, width: 760, height: 380, props: {} },
          ],
        },
        {
          id: 'sec-totals',
          type: 'TOTALS',
          label: 'Toplam',
          order: 4,
          height: 120,
          visible: true,
          elements: [
            { id: 'el-totals-table', type: 'TOTALS_TABLE', x: 440, y: 0, width: 320, height: 120, props: {} },
            { id: 'el-amount-text-label', type: 'LABEL', x: 0, y: 8, width: 120, height: 18, props: { value: 'Yazıyla:', fontSize: 10, fontWeight: '600', color: '#475569' } },
            { id: 'el-amount-text', type: 'LABEL', x: 120, y: 8, width: 310, height: 18, props: { dataBinding: 'invoice.grandTotalText', fontSize: 10, fontWeight: '600' } },
          ],
        },
        {
          id: 'sec-footer',
          type: 'FOOTER',
          label: 'Alt Bilgi',
          order: 5,
          height: 80,
          visible: true,
          elements: [
            { id: 'el-qr', type: 'QRCODE', x: 0, y: 0, width: 80, height: 80, props: { dataBinding: 'invoice.no' } },
            { id: 'el-footer-note', type: 'LABEL', x: 90, y: 20, width: 480, height: 32, props: { value: 'İşbu fatura muhteviyatına 8 gün içerisinde itiraz edilmediği takdirde aynen kabul edilmiş sayılır.', fontSize: 9, color: '#64748b', fontAlign: 'left' } },
            { id: 'el-sign-label', type: 'LABEL', x: 600, y: 0, width: 160, height: 18, props: { value: 'İmza / Kaşe', fontSize: 9, fontAlign: 'center', color: '#64748b' } },
            { id: 'el-sign-box', type: 'SIGNATURE', x: 600, y: 20, width: 160, height: 60, props: {} },
          ],
        },
      ],
      metadata: { primaryColor: '#1a56db', showPageNumbers: true },
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
      createdBy: 'system',
    },
    {
      id: 'fd-default-waybill',
      name: 'Standart İrsaliye',
      documentType: 'WAYBILL',
      description: 'Standart A4 irsaliye şablonu',
      version: 1,
      isDefault: true,
      isBuiltIn: true,
      paperSize: 'A4',
      orientation: 'portrait',
      marginTop: 10,
      marginBottom: 10,
      marginLeft: 15,
      marginRight: 15,
      sections: [
        {
          id: 'sec-header',
          type: 'HEADER',
          label: 'Başlık',
          order: 1,
          height: 120,
          visible: true,
          elements: [
            { id: 'el-logo', type: 'LOGO', x: 0, y: 0, width: 140, height: 70, props: { objectFit: 'contain' } },
            { id: 'el-company-name', type: 'LABEL', x: 160, y: 8, width: 380, height: 28, props: { dataBinding: 'company.title', fontSize: 15, fontWeight: '700' } },
            { id: 'el-title', type: 'LABEL', x: 0, y: 90, width: 760, height: 28, props: { value: 'İRSALİYE', fontSize: 13, fontWeight: '700', fontAlign: 'center', backgroundColor: '#374151', color: '#ffffff' } },
          ],
        },
        {
          id: 'sec-customer',
          type: 'CUSTOMER',
          label: 'Müşteri',
          order: 2,
          height: 80,
          visible: true,
          elements: [
            { id: 'el-wb-no', type: 'LABEL', x: 0, y: 8, width: 300, height: 18, props: { dataBinding: 'waybill.no', fontSize: 12, fontWeight: '700' } },
          ],
        },
        {
          id: 'sec-lines',
          type: 'LINES',
          label: 'Ürünler',
          order: 3,
          height: 420,
          visible: true,
          elements: [
            { id: 'el-product-table', type: 'PRODUCT_TABLE', x: 0, y: 0, width: 760, height: 420, props: {} },
          ],
        },
        {
          id: 'sec-footer',
          type: 'FOOTER',
          label: 'Alt',
          order: 4,
          height: 60,
          visible: true,
          elements: [
            { id: 'el-footer-note', type: 'LABEL', x: 0, y: 10, width: 500, height: 20, props: { value: 'Mallar tarafımca/tarafımızca teslim alınmıştır.', fontSize: 10 } },
            { id: 'el-sign', type: 'SIGNATURE', x: 580, y: 0, width: 180, height: 60, props: {} },
          ],
        },
      ],
      metadata: { primaryColor: '#374151' },
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
      createdBy: 'system',
    },
  ],
  services: [
    { id: 'srv-1', code: 'PRE_ACCOUNTING', name: 'Ön Muhasebe Temel Modülü', description: 'Cari, stok, fatura ve temel raporlar', category: 'CORE', isActive: true, price: 500, billingPeriod: 'MONTHLY', sortOrder: 1 },
    { id: 'srv-2', code: 'CARI', name: 'Cari Hesap Yönetimi', description: 'Müşteri & Tedarikçi borç/alacak takibi, ekstre', category: 'CORE', isActive: true, price: 300, billingPeriod: 'MONTHLY', sortOrder: 2 },
    { id: 'srv-3', code: 'STOK', name: 'Stok & Envanter Yönetimi', description: 'Ürün, barkod, kritik stok, depo hareketleri', category: 'CORE', isActive: true, price: 350, billingPeriod: 'MONTHLY', sortOrder: 3 },
    { id: 'srv-4', code: 'FATURA', name: 'Satış & Alış Faturaları', description: 'Resmi faturalandırma, tevkifat, iskonto', category: 'CORE', isActive: true, price: 400, billingPeriod: 'MONTHLY', sortOrder: 4 },
    { id: 'srv-5', code: 'EFATURA', name: 'e-Fatura Entegrasyonu', description: 'GİB UBL-TR 2.1 doğrudan entegratör gönderimi', category: 'EDOCUMENT', isActive: true, price: 650, billingPeriod: 'MONTHLY', sortOrder: 5 },
    { id: 'srv-6', code: 'EARSIV', name: 'e-Arşiv Fatura Entegrasyonu', description: 'Son kullanıcılara e-posta & SMS ile fatura gönderimi', category: 'EDOCUMENT', isActive: true, price: 450, billingPeriod: 'MONTHLY', sortOrder: 6 },
    { id: 'srv-7', code: 'EIRSALIYE', name: 'e-İrsaliye Entegrasyonu', description: 'Elektronik sevk ve taşıma irsaliyesi', category: 'EDOCUMENT', isActive: true, price: 450, billingPeriod: 'MONTHLY', sortOrder: 7 },
    { id: 'srv-8', code: 'EDEFTER', name: 'e-Defter & Berat Gönderimi', description: 'Yevmiye ve Kebir beratlarının GİB gönderimi', category: 'EDOCUMENT', isActive: true, price: 850, billingPeriod: 'MONTHLY', sortOrder: 8 },
    { id: 'srv-9', code: 'KASA', name: 'Kasa & Nakit Akışı', description: 'Nakit giriş/çıkış, gün sonu devri', category: 'FINANCE', isActive: true, price: 250, billingPeriod: 'MONTHLY', sortOrder: 9 },
    { id: 'srv-10', code: 'BANKA', name: 'Banka Hesapları & EFT', description: 'Banka hesapları, virman, hesap hareketleri', category: 'FINANCE', isActive: true, price: 300, billingPeriod: 'MONTHLY', sortOrder: 10 },
    { id: 'srv-11', code: 'CEK_SENET', name: 'Çek & Senet Portföyü', description: 'Müşteri/kendi çek ve senet takibi, ciro, tahsilat', category: 'FINANCE', isActive: true, price: 350, billingPeriod: 'MONTHLY', sortOrder: 11 },
    { id: 'srv-12', code: 'TEKLIF_SIPARIS', name: 'Teklif & Sipariş Modülü', description: 'Müşteri teklifleri, sipariş takibi ve faturaya dönüştürme', category: 'OPERATIONS', isActive: true, price: 400, billingPeriod: 'MONTHLY', sortOrder: 12 },
    { id: 'srv-13', code: 'IRSALIYE', name: 'İrsaliye & Sevkiyat', description: 'Matbu ve e-irsaliye yönetimi', category: 'OPERATIONS', isActive: true, price: 300, billingPeriod: 'MONTHLY', sortOrder: 13 },
    { id: 'srv-14', code: 'PERSONEL', name: 'Personel & Bordro', description: 'Maaş, avans, prim ve personel cari hesabı', category: 'OPERATIONS', isActive: true, price: 450, billingPeriod: 'MONTHLY', sortOrder: 14 },
    { id: 'srv-15', code: 'TEKNIK_SERVIS', name: 'Teknik Servis & Garanti', description: 'Cihaz kabul, servis formu ve parça takibi', category: 'OPERATIONS', isActive: true, price: 550, billingPeriod: 'MONTHLY', sortOrder: 15 },
    { id: 'srv-16', code: 'DEPO', name: 'Çoklu Depo Yönetimi', description: 'Şube ve depolar arası transfer, sayım', category: 'OPERATIONS', isActive: true, price: 350, billingPeriod: 'MONTHLY', sortOrder: 16 },
    { id: 'srv-17', code: 'RAPOR', name: 'Gelişmiş Yönetici Raporları', description: 'Kârlılık analizi, nakit akış projeksiyonu, pivot tablolar', category: 'ADVANCED', isActive: true, price: 500, billingPeriod: 'MONTHLY', sortOrder: 17 },
    { id: 'srv-18', code: 'API', name: 'REST API & Webhook', description: '3. parti yazılımlar ve e-ticaret entegrasyonu', category: 'ADVANCED', isActive: true, price: 750, billingPeriod: 'MONTHLY', sortOrder: 18 },
    { id: 'srv-19', code: 'FORM_DESIGNER', name: 'Görsel Form & Belge Tasarımcısı', description: 'Sürükle-bırak fatura, irsaliye ve makbuz tasarımcısı', category: 'ADVANCED', isActive: true, price: 350, billingPeriod: 'MONTHLY', sortOrder: 19 },
    { id: 'srv-20', code: 'AI_ASISTAN', name: 'Yapay Zeka Muhasebe Asistanı', description: 'Gemini destekli sesli komut, akıllı analiz ve tahmin', category: 'ADVANCED', isActive: true, price: 600, billingPeriod: 'MONTHLY', sortOrder: 20 },
  ],
  plans: [
    {
      id: 'plan-starter',
      code: 'STARTER',
      name: 'Başlangıç Paketi',
      description: 'Küçük işletmeler ve serbest meslek sahipleri için temel muhasebe paketi.',
      monthlyPrice: 950,
      annualPrice: 9500,
      maxUsers: 2,
      maxBranches: 1,
      maxWarehouses: 1,
      maxInvoicesPerMonth: 500,
      storageLimitMb: 1024,
      includedServices: ['PRE_ACCOUNTING', 'CARI', 'STOK', 'FATURA', 'KASA'],
    },
    {
      id: 'plan-pro',
      code: 'PRO',
      name: 'Profesyonel Paket',
      description: 'Büyüyen KOBİ\'ler için tam entegre finans, e-belge ve operasyon yönetimi.',
      monthlyPrice: 2450,
      annualPrice: 24500,
      maxUsers: 10,
      maxBranches: 3,
      maxWarehouses: 3,
      maxInvoicesPerMonth: 5000,
      storageLimitMb: 5120,
      includedServices: ['PRE_ACCOUNTING', 'CARI', 'STOK', 'FATURA', 'EFATURA', 'EARSIV', 'KASA', 'BANKA', 'TEKLIF_SIPARIS', 'IRSALIYE', 'RAPOR'],
      isPopular: true,
    },
    {
      id: 'plan-enterprise',
      code: 'ENTERPRISE',
      name: 'Kurumsal Paket',
      description: 'Büyük ölçekli işletmeler ve grup şirketleri için sınırsız güç ve AI desteği.',
      monthlyPrice: 6900,
      annualPrice: 69000,
      maxUsers: 50,
      maxBranches: 15,
      maxWarehouses: 15,
      maxInvoicesPerMonth: 50000,
      storageLimitMb: 20480,
      includedServices: [
        'PRE_ACCOUNTING', 'CARI', 'STOK', 'FATURA', 'EFATURA', 'EARSIV', 'EIRSALIYE', 'EDEFTER',
        'KASA', 'BANKA', 'CEK_SENET', 'TEKLIF_SIPARIS', 'IRSALIYE', 'PERSONEL', 'TEKNIK_SERVIS',
        'DEPO', 'RAPOR', 'API', 'FORM_DESIGNER', 'AI_ASISTAN'
      ],
    },
  ],
  sessions: [
    {
      id: 'sess-1',
      userId: 'usr-1',
      username: 'admin',
      companyId: 'tnt-isbey',
      device: 'Windows 11 PC',
      browser: 'Chrome 128.0',
      ipAddress: '127.0.0.1',
      lastActiveAt: '2026-08-20T10:30:00Z',
      isRevoked: false,
      createdAt: '2026-08-20T08:00:00Z',
    },
    {
      id: 'sess-2',
      userId: 'usr-2',
      username: 'muhasebe',
      companyId: 'tnt-isbey',
      device: 'Windows 10 Laptop',
      browser: 'Edge 127.0',
      ipAddress: '192.168.1.45',
      lastActiveAt: '2026-08-20T09:15:00Z',
      isRevoked: false,
      createdAt: '2026-08-20T09:00:00Z',
    },
  ],
  passwordResetTokens: [],
  externalCustomers: [
    {
      id: 'hbc-001',
      externalId: 'HB-10492',
      provider: 'HIZLI_BILISIM',
      companyName: 'ABC Teknoloji ve Bilişim Çözümleri Ltd. Şti.',
      title: 'ABC Teknoloji ve Bilişim Çözümleri Sanayi Ticaret Limited Şirketi',
      taxNumber: '1234567890',
      taxOffice: 'Kadıköy',
      contactName: 'Ahmet Yılmaz',
      phone: '0532 111 22 33',
      email: 'ahmet@abcteknoloji.com',
      address: 'Caferağa Mah. Moda Cad. No: 12 Kat: 2',
      city: 'İstanbul',
      district: 'Kadıköy',
      status: 'NEW',
      registeredAt: '2026-08-18T10:15:00Z',
      syncedAt: '2026-08-21T08:30:00Z',
    },
    {
      id: 'hbc-002',
      externalId: 'HB-10495',
      provider: 'HIZLI_BILISIM',
      companyName: 'Kuzey Lojistik ve Dağıtım Hizmetleri A.Ş.',
      title: 'Kuzey Uluslararası Lojistik Taşımacılık ve Dağıtım Anonim Şirketi',
      taxNumber: '9876543210',
      taxOffice: 'Ümraniye',
      contactName: 'Mehmet Kuzey',
      phone: '0542 222 33 44',
      email: 'mehmet@kuzeylojistik.com',
      address: 'Dudullu OSB 3. Cadde No: 8',
      city: 'İstanbul',
      district: 'Ümraniye',
      status: 'NEW',
      registeredAt: '2026-08-19T14:20:00Z',
      syncedAt: '2026-08-21T08:30:00Z',
    },
    {
      id: 'hbc-003',
      externalId: 'HB-10480',
      provider: 'HIZLI_BILISIM',
      companyName: 'Atlas Bilişim ve Yönetim Danışmanlığı Ltd.',
      title: 'Atlas Bilişim Teknolojileri ve Yönetim Danışmanlığı Ltd. Şti.',
      taxNumber: '5544332211',
      taxOffice: 'Maslak',
      contactName: 'Ayşe Kaya',
      phone: '0555 333 44 55',
      email: 'ayse@atlasbilisim.com',
      address: 'Büyükdere Cad. No: 195 Kule 2 Kat: 14',
      city: 'İstanbul',
      district: 'Sarıyer',
      status: 'IMPORTED',
      isbeyCompanyId: 'tnt-atlas',
      isbeyCompanyCode: 'ISB-000002',
      registeredAt: '2026-08-15T09:00:00Z',
      syncedAt: '2026-08-21T08:30:00Z',
    },
    {
      id: 'hbc-004',
      externalId: 'HB-10475',
      provider: 'HIZLI_BILISIM',
      companyName: 'Ege Gıda Sanayi ve Dış Ticaret A.Ş.',
      title: 'Ege Organik Gıda Maddeleri Üretim ve Dış Ticaret A.Ş.',
      taxNumber: '6677889900',
      taxOffice: 'Konak',
      contactName: 'Caner Ege',
      phone: '0533 444 55 66',
      email: 'caner@egegida.com.tr',
      address: 'Atatürk OSB Mah. 10002 Sokak No: 15',
      city: 'İzmir',
      district: 'Çiğli',
      status: 'USER_CREATED',
      isbeyCompanyId: 'tnt-ege',
      isbeyCompanyCode: 'ISB-000003',
      isbeyUserId: 'usr-ege-1',
      isbeyUsername: 'caner_ege',
      isActivated: true,
      registeredAt: '2026-08-10T11:45:00Z',
      syncedAt: '2026-08-21T08:30:00Z',
    },
    {
      id: 'hbc-005',
      externalId: 'HB-10502',
      provider: 'HIZLI_BILISIM',
      companyName: 'Marmara Yapı ve Mimarlık Hizmetleri Ltd. Şti.',
      title: 'Marmara Yapı Proje Tasarım ve Mühendislik Limited Şirketi',
      taxNumber: '1122334455',
      taxOffice: 'Beylikdüzü',
      contactName: 'Murat Marmara',
      phone: '0505 555 66 77',
      email: 'murat@marmarayapi.com',
      address: 'Barış Mah. E-5 Yanyol No: 78 Kat: 5',
      city: 'İstanbul',
      district: 'Beylikdüzü',
      status: 'NEW',
      registeredAt: '2026-08-20T16:10:00Z',
      syncedAt: '2026-08-21T08:30:00Z',
    },
    {
      id: 'hbc-006',
      externalId: 'HB-10510',
      provider: 'HIZLI_BILISIM',
      companyName: 'Delta Otomotiv ve Yedek Parça İthalat Ltd.',
      title: 'Delta Motorlu Araçlar Yedek Parça ve Servis Ticaret Ltd. Şti.',
      taxNumber: '3344556677',
      taxOffice: 'Nilüfer',
      contactName: 'Selin Delta',
      phone: '0536 777 88 99',
      email: 'selin@deltaoto.com',
      address: 'Küçük Sanayi Sitesi 24. Blok No: 12',
      city: 'Bursa',
      district: 'Nilüfer',
      status: 'NEW',
      registeredAt: '2026-08-21T07:50:00Z',
      syncedAt: '2026-08-21T08:30:00Z',
    },
  ],
  integrationSyncLogs: [
    {
      id: 'synclog-1',
      provider: 'HIZLI_BILISIM',
      action: 'SYNC_STARTED',
      username: 'admin',
      details: 'Hızlı Bilişim müşteri senkronizasyonu başlatıldı.',
      status: 'SUCCESS',
      createdAt: '2026-08-21T08:30:00Z',
    },
    {
      id: 'synclog-2',
      provider: 'HIZLI_BILISIM',
      action: 'CUSTOMER_IMPORTED',
      externalCustomerId: 'HB-10480',
      customerName: 'Atlas Bilişim ve Yönetim Danışmanlığı Ltd.',
      details: 'Müşteri kaydı İŞBEY Firmasına (ISB-000002) dönüştürüldü.',
      status: 'SUCCESS',
      createdAt: '2026-08-21T08:35:00Z',
    },
  ],
  hizliBilisimSettings: {
    // E-7: varsayılan TEST URL'idir; canlı URL yanıltıcı iz bırakıyordu.
    // Gerçek bağlantı adresi yalnız process.env.HIZLI_BILISIM_API_URL'den okunur.
    apiUrl: 'https://econnecttest.hizliteknoloji.com.tr',
    apiKey: process.env.HIZLI_BILISIM_API_KEY || '', // FAZ 10: hardcode kaldırıldı
    apiUsername: 'isbey_admin',
    isTestMode: true,
    autoSyncEnabled: false,
    autoSyncIntervalMinutes: 15,
    autoCreateCompany: false,
    defaultPlan: 'PRO',
    sendActivationEmail: true,
    lastSyncAt: '2026-08-21T08:30:00Z',
    lastSyncStatus: 'SUCCESS',
    totalSynced: 6,
    totalConverted: 2,
  },
  // ── FAZ 5: SAAS ABONELİK, PAKET, KONTÖR VE BAYİ SİSTEMİ ─────────────────────
  subscriptionPlans: [
    {
      id: 'plan-starter',
      slug: 'STARTER',
      name: 'Başlangıç Paketi',
      description: 'Yeni kurulan ve küçük ölçekli işletmeler için temel ön muhasebe ve e-belge çözümü.',
      monthlyPrice: 390,
      yearlyPrice: 3744, // Aylık 312 TL (%20 indirimli)
      currency: 'TRY',
      trialDays: 14,
      status: 'ACTIVE',
      displayOrder: 1,
      maxUsers: 2,
      maxCompanies: 1,
      maxProducts: 500,
      maxCustomers: 250,
      maxInvoicesPerMonth: 100,
      includedCredits: 100,
      storageLimitMb: 1024,
      activeModules: ['CARI', 'STOK', 'FATURA', 'KASA', 'EFATURA', 'EARSIV'],
      features: [
        '2 Kullanıcı & 1 Şirket',
        '100 e-Fatura / e-Arşiv Kontörü Dahil',
        'Stok, Cari, Fatura & Kasa Yönetimi',
        'Temel Raporlar & PDF/Excel Dışa Aktarma',
        '1 GB Güvenli Bulut Depolama',
      ],
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
    },
    {
      id: 'plan-pro',
      slug: 'PRO',
      name: 'Profesyonel Paket',
      description: 'Büyüyen KOBİ’ler için tam kapsamlı ERP, e-İrsaliye ve finans yönetimi.',
      monthlyPrice: 790,
      yearlyPrice: 7584, // Aylık 632 TL (%20 indirimli)
      currency: 'TRY',
      trialDays: 14,
      status: 'ACTIVE',
      displayOrder: 2,
      isPopular: true,
      maxUsers: 5,
      maxCompanies: 3,
      maxProducts: 5000,
      maxCustomers: 2000,
      maxInvoicesPerMonth: 1000,
      includedCredits: 500,
      storageLimitMb: 5120,
      activeModules: ['CARI', 'STOK', 'FATURA', 'IRSALIYE', 'TEKLIF_SIPARIS', 'KASA', 'BANKA', 'CEK_SENET', 'EFATURA', 'EARSIV', 'EIRSALIYE', 'RAPORLAR'],
      features: [
        '5 Kullanıcı & 3 Şirket (Multi-Company)',
        '500 e-Belge Kontörü Dahil',
        'e-Fatura, e-Arşiv, e-İrsaliye',
        'Teklif, Sipariş & Çek/Senet Modülü',
        'Gelişmiş KDV & Kârlılık Analizleri',
        '5 GB Güvenli Bulut Depolama',
      ],
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
    },
    {
      id: 'plan-premium',
      slug: 'PREMIUM',
      name: 'Premium Paket',
      description: 'Gelişmiş işletmeler, e-Dönüşüm ve çok şubeli mağazacılık yönetimi.',
      monthlyPrice: 1290,
      yearlyPrice: 12384, // Aylık 1032 TL (%20 indirimli)
      currency: 'TRY',
      trialDays: 14,
      status: 'ACTIVE',
      displayOrder: 3,
      maxUsers: 15,
      maxCompanies: 10,
      maxProducts: 25000,
      maxCustomers: 10000,
      maxInvoicesPerMonth: 5000,
      includedCredits: 1500,
      storageLimitMb: 20480,
      activeModules: ['POS', 'CARI', 'STOK', 'FATURA', 'IRSALIYE', 'TEKLIF_SIPARIS', 'KASA', 'BANKA', 'CEK_SENET', 'PERSONEL', 'EFATURA', 'EARSIV', 'EIRSALIYE', 'RAPORLAR', 'AI_ASISTAN', 'FORM_DESIGNER'],
      features: [
        '15 Kullanıcı & 10 Şirket / Şube',
        '1500 e-Belge Kontörü Dahil',
        'Hızlı Satış (POS) & Barkodlu Mağazacılık',
        'AI Asistan & Özel Form / Şablon Tasarımcısı',
        'Personel, Maaş & Prim Takibi',
        '20 GB Depolama & Öncelikli Destek',
      ],
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
    },
    {
      id: 'plan-enterprise',
      slug: 'ENTERPRISE',
      name: 'Kurumsal Paket',
      description: 'Holdingler, büyük dağıtım ağları ve sınırsız entegrasyon arayan kurumsal yapılar.',
      monthlyPrice: 2490,
      yearlyPrice: 23904, // Aylık 1992 TL (%20 indirimli)
      currency: 'TRY',
      trialDays: 30,
      status: 'ACTIVE',
      displayOrder: 4,
      maxUsers: 100,
      maxCompanies: 50,
      maxProducts: 100000,
      maxCustomers: 50000,
      maxInvoicesPerMonth: 50000,
      includedCredits: 5000,
      storageLimitMb: 102400,
      activeModules: ['*'],
      features: [
        'Sınırsız Kullanıcı & Çoklu Şirket Mimarisi',
        '5000 e-Belge Kontörü Dahil',
        'Özel REST API & Webhook Entegrasyonları',
        'Özel Müşteri Temsilcisi & 7/24 SLA',
        '100 GB Depolama & Özel Veritabanı Yedeği',
      ],
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
    },
  ],

  planFeatures: [
    { id: 'pf-1', planId: 'plan-starter', featureCode: 'max_users', featureName: 'Kullanıcı Sayısı', featureValue: '2', featureType: 'NUMERIC' },
    { id: 'pf-2', planId: 'plan-starter', featureCode: 'max_companies', featureName: 'Şirket Sayısı', featureValue: '1', featureType: 'NUMERIC' },
    { id: 'pf-3', planId: 'plan-starter', featureCode: 'einvoice_enabled', featureName: 'e-Fatura & e-Arşiv', featureValue: 'true', featureType: 'BOOLEAN' },
    { id: 'pf-4', planId: 'plan-starter', featureCode: 'edespatch_enabled', featureName: 'e-İrsaliye', featureValue: 'false', featureType: 'BOOLEAN' },
    { id: 'pf-5', planId: 'plan-starter', featureCode: 'api_access', featureName: 'REST API Erişimi', featureValue: 'false', featureType: 'BOOLEAN' },

    { id: 'pf-6', planId: 'plan-pro', featureCode: 'max_users', featureName: 'Kullanıcı Sayısı', featureValue: '5', featureType: 'NUMERIC' },
    { id: 'pf-7', planId: 'plan-pro', featureCode: 'max_companies', featureName: 'Şirket Sayısı', featureValue: '3', featureType: 'NUMERIC' },
    { id: 'pf-8', planId: 'plan-pro', featureCode: 'einvoice_enabled', featureName: 'e-Fatura & e-Arşiv', featureValue: 'true', featureType: 'BOOLEAN' },
    { id: 'pf-9', planId: 'plan-pro', featureCode: 'edespatch_enabled', featureName: 'e-İrsaliye', featureValue: 'true', featureType: 'BOOLEAN' },
    { id: 'pf-10', planId: 'plan-pro', featureCode: 'bank_integration', featureName: 'Banka Entegrasyonu', featureValue: 'true', featureType: 'BOOLEAN' },

    { id: 'pf-11', planId: 'plan-premium', featureCode: 'max_users', featureName: 'Kullanıcı Sayısı', featureValue: '15', featureType: 'NUMERIC' },
    { id: 'pf-12', planId: 'plan-premium', featureCode: 'max_companies', featureName: 'Şirket Sayısı', featureValue: '10', featureType: 'NUMERIC' },
    { id: 'pf-13', planId: 'plan-premium', featureCode: 'pos_sales', featureName: 'Hızlı POS Satış', featureValue: 'true', featureType: 'BOOLEAN' },
    { id: 'pf-14', planId: 'plan-premium', featureCode: 'ai_assistant', featureName: 'AI Asistan', featureValue: 'true', featureType: 'BOOLEAN' },

    { id: 'pf-15', planId: 'plan-enterprise', featureCode: 'max_users', featureName: 'Kullanıcı Sayısı', featureValue: '100', featureType: 'NUMERIC' },
    { id: 'pf-16', planId: 'plan-enterprise', featureCode: 'api_access', featureName: 'REST API Erişimi', featureValue: 'true', featureType: 'BOOLEAN' },
    { id: 'pf-17', planId: 'plan-enterprise', featureCode: 'custom_sla', featureName: 'Özel SLA Desteği', featureValue: 'true', featureType: 'BOOLEAN' },
  ],

  creditPackages: [
    { id: 'cp-100', name: '100 e-Belge Kontörü', quantity: 100, creditAmount: 100, price: 180, vatRate: 20, totalPrice: 216, unitPrice: 1.80, status: 'ACTIVE', active: true, displayOrder: 1, expiresInDays: 365 },
    { id: 'cp-250', name: '250 e-Belge Kontörü', quantity: 250, creditAmount: 250, price: 400, vatRate: 20, totalPrice: 480, unitPrice: 1.60, isPopular: true, status: 'ACTIVE', active: true, displayOrder: 2, expiresInDays: 365 },
    { id: 'cp-500', name: '500 e-Belge Kontörü', quantity: 500, creditAmount: 500, price: 700, vatRate: 20, totalPrice: 840, unitPrice: 1.40, status: 'ACTIVE', active: true, displayOrder: 3, expiresInDays: 365 },
    { id: 'cp-1000', name: '1.000 e-Belge Kontörü', quantity: 1000, creditAmount: 1000, price: 1250, vatRate: 20, totalPrice: 1500, unitPrice: 1.25, isPopular: true, status: 'ACTIVE', active: true, displayOrder: 4, expiresInDays: 730 },
    { id: 'cp-2500', name: '2.500 e-Belge Kontörü', quantity: 2500, creditAmount: 2500, price: 2750, vatRate: 20, totalPrice: 3300, unitPrice: 1.10, status: 'ACTIVE', active: true, displayOrder: 5, expiresInDays: 730 },
    { id: 'cp-5000', name: '5.000 e-Belge Kontörü', quantity: 5000, creditAmount: 5000, price: 5000, vatRate: 20, totalPrice: 6000, unitPrice: 1.00, status: 'ACTIVE', active: true, displayOrder: 6, expiresInDays: 1095 },
  ],

  subscriptions: [
    {
      id: 'sub-isbey-1',
      tenantId: 'tnt-isbey',
      planId: 'plan-enterprise',
      planSlug: 'ENTERPRISE',
      status: 'active',
      billingCycle: 'yearly',
      startDate: '2026-01-01T00:00:00Z',
      endDate: '2027-01-01T00:00:00Z',
      nextBillingDate: '2027-01-01T00:00:00Z',
      gracePeriodDays: 7,
      autoRenew: true,
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
    },
    {
      id: 'sub-atlas-1',
      tenantId: 'tnt-atlas',
      planId: 'plan-pro',
      planSlug: 'PRO',
      status: 'trial',
      billingCycle: 'monthly',
      startDate: '2026-08-15T00:00:00Z',
      endDate: '2026-08-29T00:00:00Z',
      trialStart: '2026-08-15T00:00:00Z',
      trialEnd: '2026-08-29T00:00:00Z',
      nextBillingDate: '2026-08-29T00:00:00Z',
      gracePeriodDays: 7,
      autoRenew: true,
      createdAt: '2026-08-15T00:00:00Z',
      updatedAt: '2026-08-15T00:00:00Z',
    },
  ],

  creditWallets: [
    {
      id: 'wlt-isbey',
      tenantId: 'tnt-isbey',
      balance: 943,
      reservedBalance: 0,
      lowCreditThreshold: 25,
      updatedAt: '2026-08-21T08:30:00Z',
    },
    {
      id: 'wlt-atlas',
      tenantId: 'tnt-atlas',
      balance: 100,
      reservedBalance: 0,
      lowCreditThreshold: 20,
      updatedAt: '2026-08-15T00:00:00Z',
    },
  ],

  payments: [
    {
      id: 'pay-init-1',
      tenantId: 'tnt-isbey',
      subscriptionId: 'sub-isbey-1',
      paymentProvider: 'MOCK',
      providerPaymentId: 'MOCK-TX-20260101-99881',
      orderNumber: 'ORD-2026-0001',
      amount: 23904,
      currency: 'TRY',
      vatAmount: 4780.8,
      totalAmount: 28684.8,
      status: 'successful',
      paymentType: 'SUBSCRIPTION',
      description: 'Kurumsal Paket (Yıllık) Abonelik Ödemesi',
      cardLast4: '4242',
      cardBrand: 'Mastercard',
      paidAt: '2026-01-01T10:15:00Z',
      billingInvoiceId: 'binv-2026-0001',
      createdAt: '2026-01-01T10:14:00Z',
      updatedAt: '2026-01-01T10:15:00Z',
    },
  ],

  billingInvoices: [
    {
      id: 'binv-2026-0001',
      tenantId: 'tnt-isbey',
      tenantName: 'İŞBEY Teknoloji ve Ticaret A.Ş.',
      tenantTaxNumber: '4810592817',
      tenantAddress: 'Atatürk Caddesi No: 45 Kat: 4 Kadıköy / İSTANBUL',
      subscriptionId: 'sub-isbey-1',
      paymentId: 'pay-init-1',
      invoiceNumber: 'ISB-2026-000001',
      invoiceDate: '2026-01-01T10:15:00Z',
      periodStart: '2026-01-01T00:00:00Z',
      periodEnd: '2027-01-01T00:00:00Z',
      subtotal: 23904,
      vatAmount: 4780.8,
      discountAmount: 0,
      totalAmount: 28684.8,
      currency: 'TRY',
      status: 'paid',
      paidAt: '2026-01-01T10:15:00Z',
      items: [
        {
          id: 'bitem-1',
          description: 'İŞBEY CLOUD Kurumsal Paket - 1 Yıllık Lisans Aboneliği',
          quantity: 1,
          unitPrice: 23904,
          vatRate: 20,
          vatAmount: 4780.8,
          totalAmount: 28684.8,
        },
      ],
      createdAt: '2026-01-01T10:15:00Z',
    },
  ],

  usageRecords: [
    { id: 'usg-1', tenantId: 'tnt-isbey', metric: 'users', currentValue: 3, limitValue: 100, isHardLimit: true, updatedAt: '2026-08-21T08:30:00Z' },
    { id: 'usg-2', tenantId: 'tnt-isbey', metric: 'companies', currentValue: 2, limitValue: 50, isHardLimit: true, updatedAt: '2026-08-21T08:30:00Z' },
    { id: 'usg-3', tenantId: 'tnt-isbey', metric: 'storage_mb', currentValue: 142, limitValue: 102400, isHardLimit: false, updatedAt: '2026-08-21T08:30:00Z' },
    { id: 'usg-4', tenantId: 'tnt-isbey', metric: 'einvoices', currentValue: 114, limitValue: 50000, isHardLimit: false, updatedAt: '2026-08-21T08:30:00Z' },
  ],

  dealers: [
    {
      id: 'dealer-isbey-hq',
      parentDealerId: null,
      name: 'İŞBEY Genel Merkez Bayi Ağı',
      code: 'BAYI-001',
      email: 'bayi@isbey.com.tr',
      phone: '+90 (216) 555 01 00',
      contactPerson: 'Vedat Aydın Karakaya',
      taxNumber: '4810592817',
      taxOffice: 'Kadıköy',
      city: 'İstanbul',
      commissionRate: 25, // %25
      balance: 14850,
      status: 'ACTIVE',
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
    },
    {
      id: 'dealer-marmara',
      parentDealerId: 'dealer-isbey-hq',
      name: 'Marmara Çözüm Ortakları Ltd. Şti.',
      code: 'BAYI-102',
      email: 'marmara@isbeybayi.com',
      phone: '+90 (212) 444 02 22',
      contactPerson: 'Ahmet Marmara',
      taxNumber: '9988776655',
      taxOffice: 'Şişli',
      city: 'İstanbul',
      commissionRate: 20, // %20
      balance: 4200,
      status: 'ACTIVE',
      createdAt: '2026-02-15T00:00:00Z',
      updatedAt: '2026-02-15T00:00:00Z',
    },
  ],

  dealerCommissions: [
    {
      id: 'dcom-1',
      dealerId: 'dealer-isbey-hq',
      dealerName: 'İŞBEY Genel Merkez Bayi Ağı',
      tenantId: 'tnt-isbey',
      tenantName: 'İŞBEY Teknoloji ve Ticaret A.Ş.',
      paymentId: 'pay-init-1',
      subscriptionId: 'sub-isbey-1',
      paymentAmount: 23904,
      commissionRate: 25,
      commissionAmount: 5976,
      status: 'PAID',
      notes: 'İlk yıl lisans kurulum komisyonu',
      createdAt: '2026-01-01T10:15:00Z',
      approvedAt: '2026-01-02T10:00:00Z',
      paidAt: '2026-01-05T12:00:00Z',
    },
  ],

  settings: {
    receiptHeader: 'İŞBEY TEKNOLOJİ VE TİCARET A.Ş.\nKadıköy / İstanbul - Tel: (216) 555 01 23\nVergi Dairesi: Kadıköy - VKN: 4810592817',
    receiptFooter: 'Mali değeri yoktur, bilgi fişidir.\nBizi tercih ettiğiniz için teşekkür ederiz.',
    printerType: 'THERMAL_80MM',
    enableSoundEffects: true,
    autoBackupDaily: true,
    barcodeStandard: 'EAN13',
    taxRates: [0, 1, 10, 20],
  },
};


