import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { randomBytes, createHmac } from 'node:crypto';
import express from 'express';

process.env.NODE_ENV = 'test';
process.env.JWT_SECRET = randomBytes(48).toString('hex');
process.env.E_SERVICE_WEBHOOK_SECRET = randomBytes(48).toString('hex');
process.env.DATABASE_PATH = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'isbey-eservice-')), 'test.json');
const { storage } = await import('../db/storage');
const { generateToken } = await import('../routes/auth');
const { migrateMemberships, membershipFor } = await import('../security/memberships');
const { AccountantService } = await import('../services/ai/accountantService');
const { createEServicesRouter } = await import('../routes/e-services');
const { defaultDeny } = await import('../middleware/securityGate');
const { membershipsRouter } = await import('../routes/memberships');
const { requireAuth } = await import('../middleware/authGuards');
const { menuAllowsView } = await import('../../src/data/erpMenus');
const { HizliConnectService } = await import('../services/hizliConnectService');
const { setTenantTokenForTest } = await import('../services/hizliTenantCredentialRegistry');
storage.update(db => {
  const template = db.tenants[0];
  db.tenants = ['a', 'b'].map(id => ({ ...template, id, name: id, taxNumber: id === 'a' ? '1234567890' : '1234567891', status: 'ACTIVE', isArchived: false,
    erpSubscription: { startDate: '2020-01-01', endDate: '2099-12-31', expiryPolicy: 'READ_ONLY', updatedAt: '' } }));
  db.users = ['admin', 'a', 'b', 'accountant'].map(id => ({ id, username: id, fullName: id, email: `${id}@example.test`, active: true,
    role: id === 'admin' ? 'SUPER_ADMIN' : id === 'accountant' ? 'MUHASEBE' : 'COMPANY_ADMIN', companyId: id === 'b' ? 'b' : 'a', allowedCompanyIds: [id === 'b' ? 'b' : 'a'], passwordHash: '', createdAt: new Date().toISOString() }));
  db.tenantUsers = []; migrateMemberships(db); db.eServiceApplications = [];
  // Stale portfolio rows and legacy company lists must not grant access.
  db.users.find(u => u.id === 'accountant')!.allowedCompanyIds = ['a', 'b'];
  db.accountantClients = [{ id: 'stale', tenantId: 'b', accountantUserId: 'accountant' } as any];
  db.tenantEinvoiceSettings = ['a', 'b'].map(id => ({ id, tenantId: id, providerId: 'HIZLI', environment: 'TEST', senderIdentifier: db.tenants.find(t => t.id === id)!.taxNumber,
    integrationEnabled: true, status: 'ACTIVE', createdAt: '', updatedAt: '' }));
});
const tokens = Object.fromEntries(storage.getState().users.map(u => [u.id, generateToken(u, u.companyId)]));
const app = express(); app.use(express.json()); app.use('/api', defaultDeny);
app.use('/api/members', membershipsRouter);
app.get('/api/customers', requireAuth, (_req, res) => res.json({ success: true }));
app.get('/api/v1/customers', requireAuth, (_req, res) => res.json({ success: true }));
app.get('/api/products', requireAuth, (_req, res) => res.json({ success: true }));
app.use('/api/e-services', createEServicesRouter());
let checkoutOrder: any;
app.use('/api/enabled', createEServicesRouter({ createCheckout: async order => { checkoutOrder = order; return { url: 'https://payments.example.test/checkout' }; } }));
const server = app.listen(0, '127.0.0.1'); await new Promise<void>(resolve => server.once('listening', resolve));
const base = `http://127.0.0.1:${(server.address() as import('node:net').AddressInfo).port}`;
let checks = 0;
async function call(url: string, user: string, method = 'GET', body?: unknown, status = 200, headers: Record<string, string> = {}) {
  const r = await fetch(base + url, { method, headers: { 'Content-Type': 'application/json', ...(tokens[user] ? { Authorization: `Bearer ${tokens[user]}` } : {}), ...headers }, body: body === undefined ? undefined : JSON.stringify(body) });
  const json = await r.json(); assert.equal(r.status, status, `${method} ${url}: ${JSON.stringify(json)}`); checks++; return json;
}
const root = '/api/e-services';
try {
  const ownerMembership = { roleIds: ['role-company-admin'], status: 'active', isOwner: true };
  await call('/api/members/b/memberships/b', 'admin', 'PUT', { roleIds: ['role-company-admin'], status: 'active', allowedMenuIds: ['stok'] });
  await call('/api/customers', 'b', 'GET', undefined, 403);
  await call('/api/v1/customers', 'b', 'GET', undefined, 403);
  await call('/api/products', 'b');
  assert.equal(menuAllowsView(['stok'], 'cari'), false);
  assert.equal(menuAllowsView(['stok'], 'hizmetler'), true);
  await call('/api/members/b/memberships/b', 'admin', 'PUT', { roleIds: ['role-company-admin'], status: 'active', allowedMenuIds: ['platform-admin'] }, 400);
  await call('/api/members/b/memberships/b', 'admin', 'PUT', { roleIds: ['role-company-admin'], status: 'active', allowedMenuIds: null });
  await call('/api/customers', 'b');
  const plan = storage.getState().subscriptionPlans!.find(p => p.status === 'ACTIVE')!;
  await call(`${root}/plan-requests`, 'a', 'POST', { planId: plan.id, period: 'INVALID' }, 400);
  await call(`${root}/plan-requests`, 'a', 'POST', { planId: plan.id, period: 'YEARLY', amount: 1, tenantId: 'b' }, 201);
  const planRequest = storage.getState().servicePlanRequests![0];
  assert.equal(planRequest.tenantId, 'a'); assert.equal(planRequest.amount, plan.yearlyPrice);
  await call(`${root}/plan-requests`, 'a', 'POST', { planId: plan.id, period: 'YEARLY' }, 400);
  assert.equal((await call(`${root}/plan-requests`, 'b')).requests.length, 0);
  await call('/api/members/a/memberships/a', 'admin', 'PUT', ownerMembership);
  await call('/api/members/a/memberships/b', 'admin', 'PUT', ownerMembership);
  assert.equal(storage.getState().tenantUsers!.filter(m => m.userId === 'a' && m.isOwner).length, 2);
  await call('/api/members/b/memberships/b', 'a', 'PUT', ownerMembership, 403);
  await call('/api/members/b/memberships/b', 'admin', 'PUT', { ...ownerMembership, roleIds: ['role-accountant'] }, 400);
  await call(`${root}/applications`, '', 'GET', undefined, 401);
  const input = { contactName: 'Test', email: 'test@example.test', phone: '05555555555', services: ['EFATURA'], consent: true, tenantId: 'b', amountMinor: 1, status: 'PAID' };
  await call(`${root}/applications`, 'a', 'POST', { ...input, consent: false }, 400);
  const { application: a } = await call(`${root}/applications`, 'a', 'POST', input, 201);
  assert.equal(a.tenantId, 'a'); assert.equal(a.status, 'SUBMITTED'); assert.equal(a.amountMinor, undefined);
  await call(`${root}/applications`, 'a', 'POST', input, 400);
  assert.equal((await call(`${root}/applications`, 'b')).applications.length, 0);
  await call(`${root}/applications/${a.id}/quote`, 'a', 'POST', { amountMinor: 10000 }, 403);
  await call(`${root}/applications/${a.id}/quote`, 'admin', 'POST', { amountMinor: -1 }, 400);
  const { application: quoted } = await call(`${root}/applications/${a.id}/quote`, 'admin', 'POST', { amountMinor: 10000 });
  await call(`${root}/applications/${a.id}/quote`, 'admin', 'POST', { amountMinor: 20000 }, 400);
  await call(`${root}/applications/${a.id}/checkout`, 'b', 'POST', {}, 404);
  await call(`${root}/applications/${a.id}/checkout`, 'a', 'POST', {}, 503);
  await call(`/api/enabled/applications/${a.id}/checkout`, 'a', 'POST', { amountMinor: 1 });
  assert.equal(checkoutOrder.amountMinor, 10000); assert.equal(checkoutOrder.orderId, quoted.orderId);
  const callback = { orderId: quoted.orderId, amountMinor: 10000, currency: 'TRY', reference: 'payment-1', timestamp: Date.now() };
  const sign = (c: typeof callback) => createHmac('sha256', process.env.E_SERVICE_WEBHOOK_SECRET!).update(JSON.stringify([c.orderId, c.amountMinor, c.currency, c.reference, c.timestamp])).digest('hex');
  await call(`${root}/payment-callback`, '', 'POST', callback, 401);
  await call(`${root}/payment-callback`, '', 'POST', { ...callback, amountMinor: 1 }, 401, { 'x-payment-signature': sign(callback) });
  const wrong = { ...callback, amountMinor: 1 };
  await call(`${root}/payment-callback`, '', 'POST', wrong, 400, { 'x-payment-signature': sign(wrong) });
  await call(`${root}/payment-callback`, '', 'POST', callback, 200, { 'x-payment-signature': sign(callback) });
  await call(`${root}/payment-callback`, '', 'POST', callback, 200, { 'x-payment-signature': sign(callback) });
  assert.equal(storage.getState().eServiceApplications?.[0].status, 'PAID');
  await call(`${root}/applications/${a.id}/checkout`, 'a', 'POST', {}, 409);
  const expired = { ...callback, timestamp: Date.now() - 600_000 };
  await call(`${root}/payment-callback`, '', 'POST', expired, 401, { 'x-payment-signature': sign(expired) });
  assert.deepEqual(AccountantService.getClients('accountant').map(c => c.tenantId), ['a']);
  assert.equal(AccountantService.isAccountantAuthorizedForTenant('accountant', 'b'), false);
  storage.update(db => { membershipFor(db, 'accountant', 'a')!.status = 'passive'; });
  assert.equal(AccountantService.getClients('accountant').length, 0);
  assert.equal(AccountantService.isAccountantAuthorizedForTenant('accountant', 'a'), false);
  setTenantTokenForTest('a', true, 'only-a'); setTenantTokenForTest('b', true, 'only-b');
  const usedTokens: string[] = [];
  HizliConnectService.getDocumentList = async (_params, token) => { usedTokens.push(token); return { success: true, documents: [{ DocumentId: 'INV1', UUID: 'uuid', password: 'must-not-leak' }] }; };
  const history = '?startDate=2026-01-01&endDate=2026-01-31';
  const result = await call(`${root}/invoice-history${history}&tenantId=b`, 'a');
  assert.equal(result.documents[0].number, 'INV1'); assert.equal(result.documents[0].password, undefined);
  await call(`${root}/invoice-history${history}`, 'b'); assert.deepEqual(usedTokens, ['only-a', 'only-b']);
  await call(`${root}/invoice-history?startDate=wrong&endDate=wrong`, 'a', 'GET', undefined, 400);
  storage.update(db => { db.tenantEinvoiceSettings![0].senderIdentifier = '1234567891'; });
  await call(`${root}/invoice-history${history}`, 'a', 'GET', undefined, 409);
  assert.deepEqual(usedTokens, ['only-a', 'only-b'], 'Yanlış gönderici kimliğiyle sağlayıcı çağrılmamalı.');
  storage.update(db => { db.tenantEinvoiceSettings![0].senderIdentifier = '1234567890'; });
  storage.update(db => { db.tenantEinvoiceSettings![0].integrationEnabled = false; });
  await call(`${root}/invoice-history${history}`, 'a', 'GET', undefined, 409);
  console.log(`e-Service applications, payment and portfolio: ${checks} HTTP checks PASS`);
} finally { await new Promise<void>(resolve => server.close(() => resolve())); }
