import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { randomBytes } from 'node:crypto';
import express from 'express';

process.env.NODE_ENV = 'test';
process.env.JWT_SECRET = randomBytes(48).toString('hex');
process.env.DATABASE_PATH = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'isbey-entitlements-')), 'test.json');
const { storage } = await import('../db/storage');
const { generateToken, authRouter } = await import('../routes/auth');
const { migrateMemberships, membershipFor } = await import('../security/memberships');
const { requireAuth } = await import('../middleware/authGuards');
const { defaultDeny } = await import('../middleware/securityGate');
const { createEServicesRouter } = await import('../routes/e-services');
const { hizliBilisimRouter } = await import('../routes/hizli-bilisim');
const { HizliBilisimSyncService } = await import('../services/hizliBilisim/hizliBilisimSyncService');
const { HizliDealerPortal } = await import('../services/hizliBilisim/hizliDealerPortal');
const { serviceAllowsView } = await import('../../src/data/serviceAccess');
storage.update(db => {
  const template = db.tenants[0];
  db.tenants = ['a', 'b'].map(id => ({ ...template, id, taxNumber: id === 'a' ? '1111111111' : '2222222222', isArchived: false, status: 'TRIAL', selectedServicePlanIds: [], activeModules: [], erpSubscription: { startDate: '2020-01-01', endDate: '2099-12-31', expiryPolicy: 'READ_ONLY', updatedAt: '' } }));
  db.users = ['admin', 'a', 'b'].map(id => ({ id, username: id, fullName: id, email: `${id}@example.test`, active: true, role: id === 'admin' ? 'SUPER_ADMIN' : 'COMPANY_ADMIN', companyId: id === 'b' ? 'b' : 'a', allowedCompanyIds: [id === 'b' ? 'b' : 'a'], passwordHash: '', createdAt: new Date().toISOString() }));
  db.tenantUsers = []; migrateMemberships(db);
  const plan = db.subscriptionPlans![0];
  db.subscriptionPlans = [{ ...plan, id: 'cari', status: 'ACTIVE', activeModules: ['CARI'] }, { ...plan, id: 'stok', status: 'ACTIVE', activeModules: ['STOK'] }, { ...plan, id: 'efatura', status: 'ACTIVE', activeModules: ['EFATURA', 'EARSIV'] }, { ...plan, id: 'irsaliye', status: 'ACTIVE', activeModules: ['EIRSALIYE'] }, { ...plan, id: 'closed', status: 'PASSIVE', activeModules: ['*'] }];
  db.externalCustomers = [{ id: 'ext', provider: 'HIZLI_BILISIM', externalId: 'hb-test', companyName: 'Test Portfolio', title: 'Test Portfolio', taxNumber: '3333333333', contactName: 'Test Yetkili', email: 'portfolio@example.test', status: 'NEW', active: true, services: [] } as any];
});
const tokens = Object.fromEntries(storage.getState().users.map(u => [u.id, generateToken(u, u.companyId)]));
const app = express(); app.use(express.json()); app.use('/api', defaultDeny);
app.use('/api/auth', authRouter); app.use('/api/e-services', createEServicesRouter()); app.use('/api/admin/hizli-bilisim', hizliBilisimRouter);
for (const resource of ['customers', 'products', 'banks', 'search', 'v1/customers', 'v1/products', 'edefter', 'v1/e-documents/incoming-despatches/list']) app.all(`/api/${resource}`, requireAuth, (_req, res) => res.json({ success: true }));
const server = app.listen(0, '127.0.0.1'); await new Promise<void>(resolve => server.once('listening', resolve));
const base = `http://127.0.0.1:${(server.address() as import('node:net').AddressInfo).port}`;
let checks = 0;
async function call(url: string, user: string, method = 'GET', body?: unknown, status = 200) {
  const response = await fetch(base + url, { method, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${tokens[user]}` }, body: body === undefined ? undefined : JSON.stringify(body) });
  const json = await response.json(); assert.equal(response.status, status, `${method} ${url}: ${JSON.stringify(json)}`); checks++; return json;
}
try {
  const registered = await call('/api/auth/register', '', 'POST', { fullName: 'Test Üye', email: 'registration@example.test', companyName: 'Paket Seçim Firması', taxNumber: '5555555555', password: 'SecureTest123!' }, 201);
  tokens.registered = registered.token;
  assert.deepEqual(registered.user.serviceMenuIds, []);
  await call('/api/customers', 'registered', 'GET', undefined, 403);
  await call('/api/e-services/select-plans', 'registered', 'POST', { planIds: ['efatura'] });
  await call('/api/edefter', 'registered', 'GET', undefined, 403);
  await call('/api/v1/e-documents/incoming-despatches/list', 'registered', 'GET', undefined, 403);
  await call('/api/e-services/select-plans', 'registered', 'POST', { planIds: ['efatura', 'irsaliye'] });
  await call('/api/v1/e-documents/incoming-despatches/list', 'registered');
  await call('/api/e-services/select-plans', 'registered', 'POST', { planIds: ['stok'] });
  await call('/api/products', 'registered');
  await call('/api/customers', 'registered', 'GET', undefined, 403);
  await call('/api/customers', 'a', 'GET', undefined, 403);
  for (const ids of [[], ['missing'], ['closed'], ['cari', 3]]) await call('/api/e-services/select-plans', 'a', 'POST', { planIds: ids }, 400);
  await call('/api/e-services/select-plans', 'a', 'POST', { planIds: ['cari', 'cari'] });
  assert.deepEqual(storage.getState().tenants[0].selectedServicePlanIds, ['cari']);
  const me = await call('/api/auth/me', 'a'); assert.deepEqual(me.user.serviceMenuIds, ['cari']);
  assert.equal(serviceAllowsView(me.user.serviceMenuIds, 'banka'), false);
  assert.equal(serviceAllowsView(me.user.serviceMenuIds, 'cari'), true);
  for (const method of ['GET', 'POST']) {
    await call('/api/customers', 'a', method, method === 'POST' ? {} : undefined);
    await call('/api/products', 'a', method, method === 'POST' ? {} : undefined, 403);
  }
  await call('/api/v1/products', 'a', 'GET', undefined, 403);
  await call('/api/customers', 'b', 'GET', undefined, 403);
  await call('/api/e-services/select-plans', 'a', 'POST', { planIds: ['cari', 'stok'], tenantId: 'b' });
  await call('/api/v1/products', 'a');
  assert.deepEqual(storage.getState().tenants[1].selectedServicePlanIds, []);
  await call('/api/search', 'a', 'GET', undefined, 403);
  storage.update(db => { membershipFor(db, 'a', 'a')!.allowedMenuIds = ['stok']; });
  await call('/api/customers', 'a', 'GET', undefined, 403); await call('/api/products', 'a');
  storage.update(db => { db.tenants[0].status = 'ACTIVE'; });
  await call('/api/e-services/select-plans', 'a', 'POST', { planIds: ['cari'] });
  await call('/api/e-services/select-plans', 'admin', 'POST', { planIds: ['cari'] });
  await call('/api/banks', 'admin');
  let queries = 0;
  const original = HizliBilisimSyncService.sorgula;
  HizliBilisimSyncService.sorgula = async taxId => { queries++; return { success: false, durum: 'BULUNAMADI', message: `${taxId} bulunamadı.` }; };
  const before = JSON.stringify(storage.getState());
  const preview = '/api/admin/hizli-bilisim/customers/portfolio-preview';
  await call(preview, 'a', 'POST', { taxIds: ['3333333333'] }, 403);
  await call(preview, 'admin', 'POST', { taxIds: ['wrong'] }, 400); assert.equal(queries, 0);
  const r = await call(preview, 'admin', 'POST', { taxIds: ['3333333333', '3333333333', '44444444444'] });
  assert.equal(r.results.length, 2); assert.equal(queries, 2); assert.equal(JSON.stringify(storage.getState()), before);
  HizliBilisimSyncService.sorgula = original;
  const originalList = HizliDealerPortal.prototype.list;
  HizliDealerPortal.prototype.list = async (_start, _length, _search, taxId) => ({ total: 1, filtered: 1, customers: taxId === '7777777777' ? [] : [{ externalId: '999', taxNumber: '6666666666', companyName: 'Provider Firma', city: '', dealerName: 'Bayi', isActive: true, contactName: '', email: '', phone: '' }] });
  const listUrl = '/api/admin/hizli-bilisim/customers/dealer-portfolio';
  await call(listUrl, 'a', 'GET', undefined, 403);
  const dealerRows = await call(listUrl, 'admin'); assert.equal(dealerRows.total, 1);
  const importUrl = '/api/admin/hizli-bilisim/customers/dealer-import';
  await call(importUrl, 'a', 'POST', { taxIds: ['6666666666'] }, 403);
  await call(importUrl, 'admin', 'POST', { taxIds: ['invalid'] }, 400);
  const tenantCount = storage.getState().tenants.length;
  const imported = await call(importUrl, 'admin', 'POST', { taxIds: ['6666666666', '7777777777'], companyName: 'Untrusted name' });
  assert.deepEqual(imported.results.map((r: any) => r.success), [true, false]);
  assert.equal(storage.getState().externalCustomers?.find(c => c.taxNumber === '6666666666')?.companyName, 'Provider Firma');
  await call(importUrl, 'admin', 'POST', { taxIds: ['6666666666'] });
  assert.equal(storage.getState().externalCustomers?.filter(c => c.taxNumber === '6666666666').length, 1);
  assert.equal(storage.getState().tenants.length, tenantCount);
  HizliDealerPortal.prototype.list = originalList;
  const convert = '/api/admin/hizli-bilisim/create-company';
  await call(convert, 'admin', 'POST', { customerId: 'ext', planIds: ['missing'] }, 400);
  const created = await call(convert, 'admin', 'POST', { customerId: 'ext', planIds: ['stok'], isTrial: true });
  assert.deepEqual(created.company.selectedServicePlanIds, ['stok']); assert.equal('passwordHash' in created.user, false);
  assert.match(created.activationLink, /act_[a-f0-9]{64}/);
  const newUser = storage.getState().users.find(u => u.id === created.user.id)!;
  tokens.new = generateToken(newUser, created.company.id);
  await call('/api/products', 'new'); await call('/api/customers', 'new', 'GET', undefined, 403);
  await call(convert, 'admin', 'POST', { customerId: 'ext', planIds: ['stok'] }, 400);
  console.log(`Service entitlements: ${checks} HTTP checks PASS`);
} finally { server.close(); }
